-- ============================================================
-- Database Schema: LegacyFinApp-026 — Greeting Generation System
-- Project:         copilot-test-ktruchcz
-- Application:     Hello World (com.example:hello-world:1.0.0)
-- Dialect:         PostgreSQL 15+
-- Generated by:    ddl-generator agent
-- Generated at:    2025-01-01T00:00:00Z
-- Source analysis: analysis_results.json, business_rules_extractor_analysis.json,
--                  ast_analysis.json
--
-- NOTES ON FILE LOCATION:
--   Requested output path was output/database_schema.sql but the output/
--   directory did not exist and could not be auto-created.  File saved to
--   workspace root instead (same pattern used by ast-analyzer agent).
--   See analysis_output/ddl-generator/schema_documentation.md for full docs.
--
-- Description:
--   This schema provides the relational database backing that would support
--   LegacyFinApp-026 if its current in-memory/hard-coded GreetingRepository were
--   replaced with a persistent data store.  It captures four domain entities
--   identified during static analysis:
--
--     1. greeting_templates  — configurable message format strings (GreetingRepository)
--     2. recipients          — named greeting targets with default-value semantics
--     3. greeting_events     — immutable audit log of every greeting produced
--     4. app_config          — key/value application settings
--
--   Every business rule extracted (BR-001 … BR-014) and every workflow step
--   (WF-001 … WF-003) are represented either as a column, constraint, index,
--   seed-data row, or view defined below.
-- ============================================================

-- ============================================================
-- EXTENSIONS (idempotent)
-- ============================================================
-- pgcrypto supplies gen_random_uuid() used in future-proof UUID columns
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- UTILITY FUNCTION — auto-update updated_at timestamp
-- Referenced by triggers on greeting_templates, recipients, app_config
-- ============================================================
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION fn_set_updated_at() IS
    'Generic trigger function that stamps updated_at on every UPDATE operation. '
    'Attached to all mutable tables that carry an updated_at column.';


-- ============================================================
-- TABLE: greeting_templates
-- ============================================================
-- Stores the configurable message format strings used by GreetingService to
-- produce greetings.  In the current code, GreetingRepository.getGreetingTemplate()
-- returns the hard-coded string "Hello %s".  Persisting templates here allows
-- operators to introduce new greeting styles (e.g. "Hi %s", "Dear %s") without
-- redeployment.
--
-- Business rules encoded:
--   BR-012  The canonical default template value is 'Hello %s'.
--   BR-014  A template must contain exactly one Java-style positional string
--           placeholder (%s) so that String.formatted() receives exactly one
--           recipient argument.
-- ============================================================
CREATE TABLE greeting_templates (
    -- ---- identity ----
    template_id       BIGSERIAL         PRIMARY KEY,

    -- Logical lookup key used by application code (e.g. 'DEFAULT_HELLO').
    -- Unique so the service can resolve a template by name without ambiguity.
    template_key      VARCHAR(100)      NOT NULL,

    -- The actual Java format string, e.g. 'Hello %s'.
    -- Must contain exactly one %s placeholder (BR-014).
    template_value    VARCHAR(500)      NOT NULL,

    -- Cached count of %s occurrences; must equal 1 (BR-014).
    -- Stored as a column to allow a simple CHECK without regex support.
    placeholder_count INTEGER           NOT NULL DEFAULT 1,

    -- Human-readable description of this template's intended use.
    description       TEXT,

    -- Soft-delete / deactivation flag.  Only is_active = TRUE templates are
    -- returned to callers.  Allows retiring old templates without data loss.
    is_active         BOOLEAN           NOT NULL DEFAULT TRUE,

    -- Marks rows that were installed automatically at schema initialisation
    -- time and must not be deleted or deactivated by normal application flows.
    is_system         BOOLEAN           NOT NULL DEFAULT FALSE,

    -- ---- audit ----
    created_at        TIMESTAMP         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP         NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- ---- constraints ----

    -- BR-014: exactly one placeholder per template
    CONSTRAINT chk_greeting_templates_placeholder_count
        CHECK (placeholder_count = 1),

    -- BR-014: the format string must literally contain '%s'
    CONSTRAINT chk_greeting_templates_value_has_placeholder
        CHECK (template_value LIKE '%' || '%s' || '%'),

    -- template_key must be unique across all templates so the application
    -- can resolve templates by key without ambiguity
    CONSTRAINT uq_greeting_templates_key
        UNIQUE (template_key)
);

-- Indexes for greeting_templates
-- Lookup by key is the primary access pattern (GreetingRepository.getGreetingTemplate)
CREATE INDEX idx_greeting_templates_key      ON greeting_templates (template_key);
CREATE INDEX idx_greeting_templates_active   ON greeting_templates (is_active);
-- Composite: fetch the active template for a given key in a single index scan
CREATE INDEX idx_greeting_templates_key_active
    ON greeting_templates (template_key, is_active)
    WHERE is_active = TRUE;

-- Table/column comments
COMMENT ON TABLE  greeting_templates IS
    'Configurable greeting format strings. Backs GreetingRepository.getGreetingTemplate(). '
    'BR-012: default value is ''Hello %s''. BR-014: exactly one %s placeholder per template.';

COMMENT ON COLUMN greeting_templates.template_id       IS 'Surrogate primary key — auto-incremented.';
COMMENT ON COLUMN greeting_templates.template_key      IS 'Unique logical identifier used by application code to look up a template, e.g. ''DEFAULT_HELLO''.';
COMMENT ON COLUMN greeting_templates.template_value    IS 'Java String.format() compatible template, e.g. ''Hello %s''. Must contain exactly one %%s placeholder (BR-014).';
COMMENT ON COLUMN greeting_templates.placeholder_count IS 'Number of %%s placeholders in template_value. Constrained to 1 (BR-014).';
COMMENT ON COLUMN greeting_templates.description       IS 'Human-readable purpose of this template.';
COMMENT ON COLUMN greeting_templates.is_active         IS 'FALSE = template is retired and must not be used for new greetings.';
COMMENT ON COLUMN greeting_templates.is_system         IS 'TRUE = installed by schema initialisation; protected from deletion by application logic.';
COMMENT ON COLUMN greeting_templates.created_at        IS 'Wall-clock timestamp when this row was inserted.';
COMMENT ON COLUMN greeting_templates.updated_at        IS 'Wall-clock timestamp of the most recent UPDATE; maintained by trigger trg_greeting_templates_updated_at.';

-- Auto-update trigger
CREATE TRIGGER trg_greeting_templates_updated_at
    BEFORE UPDATE ON greeting_templates
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();


-- ============================================================
-- TABLE: recipients
-- ============================================================
-- Represents the named targets of greetings — i.e. the resolved value that
-- fills the %s placeholder.  GreetingRepository.getDefaultRecipient() currently
-- returns the hard-coded string "World".  Persisting recipients here allows
-- the application to maintain a catalogue of known recipients and define a
-- configurable default.
--
-- Business rules encoded:
--   BR-008  Null recipient → use default recipient.
--   BR-009  Blank recipient → use default recipient.
--   BR-010  Non-blank recipient name is stored trimmed; leading/trailing whitespace
--           is removed before persistence.
--   BR-013  The canonical default recipient is 'World'.
--           Enforced by partial unique index: only one row may have is_default = TRUE.
-- ============================================================
CREATE TABLE recipients (
    -- ---- identity ----
    recipient_id      BIGSERIAL         PRIMARY KEY,

    -- The trimmed recipient name (BR-010). e.g. 'World', 'Copilot', 'Alice'.
    -- Stored with leading/trailing whitespace removed.
    recipient_name    VARCHAR(255)      NOT NULL,

    -- Human-friendly display name.  Defaults to recipient_name when NULL.
    display_name      VARCHAR(255),

    -- Marks the system-level fallback recipient (BR-013: 'World').
    -- Only ONE row may have is_default = TRUE (enforced by partial unique index below).
    is_default        BOOLEAN           NOT NULL DEFAULT FALSE,

    -- How this recipient entry was introduced:
    --   SYSTEM  — installed by schema seed (i.e. 'World')
    --   CLI     — first seen as a command-line argument
    --   MANUAL  — inserted by an operator or admin interface
    --   API     — received via an HTTP or message-queue interface
    source            VARCHAR(20)       NOT NULL DEFAULT 'MANUAL',

    -- Soft-delete flag; inactive recipients cannot be resolved by the service.
    is_active         BOOLEAN           NOT NULL DEFAULT TRUE,

    -- ---- audit ----
    created_at        TIMESTAMP         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP         NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- ---- constraints ----

    -- BR-010: recipient_name must not be blank after trimming.
    CONSTRAINT chk_recipients_name_not_blank
        CHECK (TRIM(recipient_name) <> ''),

    -- Source must be one of the defined enum values.
    CONSTRAINT chk_recipients_source
        CHECK (source IN ('SYSTEM', 'CLI', 'MANUAL', 'API'))
);

-- Indexes for recipients
CREATE INDEX idx_recipients_name        ON recipients (recipient_name);
CREATE INDEX idx_recipients_is_default  ON recipients (is_default);
CREATE INDEX idx_recipients_active      ON recipients (is_active);
-- Composite: find the active default in one scan (BR-008, BR-009, BR-013)
CREATE INDEX idx_recipients_default_active
    ON recipients (is_default, is_active)
    WHERE is_default = TRUE AND is_active = TRUE;
-- Case-insensitive name lookup (useful for CLI matching)
CREATE INDEX idx_recipients_name_lower  ON recipients (LOWER(recipient_name));

-- BR-013 enforcement: at most one row may be the default recipient.
-- A partial unique index on a boolean column achieves this without a trigger.
CREATE UNIQUE INDEX uq_recipients_single_default
    ON recipients (is_default)
    WHERE is_default = TRUE;

-- Table/column comments
COMMENT ON TABLE  recipients IS
    'Catalogue of greeting targets. Backs GreetingRepository.getDefaultRecipient(). '
    'BR-013: system default is ''World''. BR-010: names are stored trimmed. '
    'Only one row may have is_default = TRUE (partial unique index uq_recipients_single_default).';

COMMENT ON COLUMN recipients.recipient_id   IS 'Surrogate primary key — auto-incremented.';
COMMENT ON COLUMN recipients.recipient_name IS 'Trimmed recipient name used in the greeting output (BR-010). Must not be blank (BR-009).';
COMMENT ON COLUMN recipients.display_name   IS 'Optional display override; falls back to recipient_name when NULL.';
COMMENT ON COLUMN recipients.is_default     IS 'TRUE = this is the fallback recipient when no valid input is supplied (BR-008, BR-009, BR-013). Exactly one row may be TRUE.';
COMMENT ON COLUMN recipients.source         IS 'Origin of this record: SYSTEM (seed), CLI (command-line arg), MANUAL (operator), API.';
COMMENT ON COLUMN recipients.is_active      IS 'FALSE = recipient is retired and must not be resolved by GreetingService.';
COMMENT ON COLUMN recipients.created_at     IS 'Wall-clock timestamp when this row was inserted.';
COMMENT ON COLUMN recipients.updated_at     IS 'Wall-clock timestamp of the most recent UPDATE; maintained by trigger trg_recipients_updated_at.';

-- Auto-update trigger
CREATE TRIGGER trg_recipients_updated_at
    BEFORE UPDATE ON recipients
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();


-- ============================================================
-- TABLE: greeting_events
-- ============================================================
-- Immutable audit log recording every greeting produced by GreetingService.
-- Captures the full lifecycle from raw CLI input through resolution strategy
-- to final output string, enabling analytics, replay, and audit.
--
-- Business rules encoded:
--   BR-001  When no args → resolution_strategy = 'DEFAULT_USED'.
--   BR-002  Output written to stdout → output_channel = 'STDOUT'.
--   BR-005  Empty args array → args_count = 0, resolution_strategy = 'DEFAULT_USED'.
--   BR-006  Only args[0] used → captured as requested_recipient; args_count records total.
--   BR-008  Null recipient → resolution_strategy = 'DEFAULT_USED'.
--   BR-009  Blank recipient → resolution_strategy = 'BLANK_FALLBACK'.
--   BR-010  Non-blank trimmed → resolution_strategy = 'NAMED_RECIPIENT'.
--   BR-011  Final greeting = template applied to resolved recipient.
--   WF-001  Default Greeting Workflow → workflow_id = 'WF-001'.
--   WF-002  Named Recipient Workflow  → workflow_id = 'WF-002'.
--   WF-003  Blank Recipient Fallback  → workflow_id = 'WF-003'.
-- ============================================================
CREATE TABLE greeting_events (
    -- ---- identity ----
    event_id             BIGSERIAL       PRIMARY KEY,

    -- Reference to the template row used to produce this greeting (BR-011, BR-012).
    template_id          BIGINT          NOT NULL,

    -- Reference to a known recipient row, if the resolved recipient is in the
    -- recipients catalogue.  NULL when the recipient was an ad-hoc CLI value
    -- that has not yet been registered.
    recipient_id         BIGINT,

    -- ---- input capture ----

    -- Raw value passed as args[0] to GreetingController.greet().
    -- NULL when args was null or empty (BR-004, BR-005).
    -- Stored verbatim — before any trimming or fallback — for full auditability.
    requested_recipient  VARCHAR(255),

    -- Total number of CLI arguments received.  0 = no args provided (BR-005).
    args_count           INTEGER         NOT NULL DEFAULT 0,

    -- ---- resolution ----

    -- The recipient name actually used in the greeting after all resolution
    -- logic has been applied (trim / default fallback).  Always non-blank.
    resolved_recipient   VARCHAR(255)    NOT NULL,

    -- Describes which recipient-resolution path was taken (maps to workflows):
    --   DEFAULT_USED     — null/empty args → default recipient applied (WF-001, BR-001/BR-008)
    --   NAMED_RECIPIENT  — valid args[0] provided, trimmed and used directly (WF-002, BR-010)
    --   BLANK_FALLBACK   — args[0] was blank → default recipient applied (WF-003, BR-009)
    resolution_strategy  VARCHAR(30)     NOT NULL,

    -- Workflow identifier that produced this event (WF-001, WF-002, or WF-003).
    workflow_id          VARCHAR(20),

    -- ---- output ----

    -- The complete formatted greeting string that was output (BR-002, BR-011).
    generated_greeting   TEXT            NOT NULL,

    -- Channel to which the greeting was written.
    -- STDOUT is the only channel in the current implementation (BR-002).
    output_channel       VARCHAR(20)     NOT NULL DEFAULT 'STDOUT',

    -- ---- audit ----
    -- Immutable; no updated_at because greeting_events rows are never modified.
    created_at           TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- ---- foreign keys ----
    CONSTRAINT fk_greeting_events_template
        FOREIGN KEY (template_id)
        REFERENCES greeting_templates (template_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_greeting_events_recipient
        FOREIGN KEY (recipient_id)
        REFERENCES recipients (recipient_id)
        ON DELETE SET NULL,

    -- ---- check constraints ----
    CONSTRAINT chk_greeting_events_resolution_strategy
        CHECK (resolution_strategy IN ('DEFAULT_USED', 'NAMED_RECIPIENT', 'BLANK_FALLBACK')),

    CONSTRAINT chk_greeting_events_output_channel
        CHECK (output_channel IN ('STDOUT', 'STDERR', 'FILE', 'DATABASE', 'API')),

    CONSTRAINT chk_greeting_events_args_count
        CHECK (args_count >= 0),

    CONSTRAINT chk_greeting_events_resolved_recipient_not_blank
        CHECK (TRIM(resolved_recipient) <> ''),

    -- BLANK_FALLBACK implies requested_recipient was present but blank (BR-009)
    CONSTRAINT chk_greeting_events_blank_fallback_consistency
        CHECK (
            resolution_strategy <> 'BLANK_FALLBACK'
            OR (requested_recipient IS NOT NULL AND TRIM(requested_recipient) = '')
        )
);

-- Indexes for greeting_events
CREATE INDEX idx_greeting_events_template_id   ON greeting_events (template_id);
CREATE INDEX idx_greeting_events_recipient_id  ON greeting_events (recipient_id);
CREATE INDEX idx_greeting_events_created_at    ON greeting_events (created_at DESC);
CREATE INDEX idx_greeting_events_strategy      ON greeting_events (resolution_strategy);
CREATE INDEX idx_greeting_events_workflow       ON greeting_events (workflow_id);
CREATE INDEX idx_greeting_events_template_time
    ON greeting_events (template_id, created_at DESC);
CREATE INDEX idx_greeting_events_recipient_time
    ON greeting_events (recipient_id, created_at DESC)
    WHERE recipient_id IS NOT NULL;

-- Table/column comments
COMMENT ON TABLE  greeting_events IS
    'Immutable audit log of every greeting produced by GreetingService.createGreeting(). '
    'Rows are INSERT-only; no UPDATE or DELETE is permitted in normal operation. '
    'Covers all three workflows: WF-001 (default), WF-002 (named), WF-003 (blank fallback).';

COMMENT ON COLUMN greeting_events.event_id            IS 'Surrogate primary key — auto-incremented.';
COMMENT ON COLUMN greeting_events.template_id         IS 'FK → greeting_templates. The template used to format this greeting (BR-011, BR-012).';
COMMENT ON COLUMN greeting_events.recipient_id        IS 'FK → recipients. NULL when the recipient is ad-hoc and not in the catalogue.';
COMMENT ON COLUMN greeting_events.requested_recipient IS 'Verbatim args[0] value received by GreetingController.greet(). NULL if no args were supplied (BR-004, BR-005).';
COMMENT ON COLUMN greeting_events.args_count          IS 'Total number of CLI arguments passed. 0 = invoked without arguments (BR-001, BR-005).';
COMMENT ON COLUMN greeting_events.resolved_recipient  IS 'Final recipient name used after trim/default resolution (BR-008, BR-009, BR-010). Always non-blank.';
COMMENT ON COLUMN greeting_events.resolution_strategy IS 'Resolution path taken: DEFAULT_USED (WF-001), NAMED_RECIPIENT (WF-002), BLANK_FALLBACK (WF-003).';
COMMENT ON COLUMN greeting_events.workflow_id         IS 'Identifier of the workflow that produced this event (WF-001, WF-002, WF-003).';
COMMENT ON COLUMN greeting_events.generated_greeting  IS 'Complete greeting string written to the output channel, e.g. ''Hello World'' (BR-002, BR-011).';
COMMENT ON COLUMN greeting_events.output_channel      IS 'Destination for the greeting output. STDOUT in the current implementation (BR-002).';
COMMENT ON COLUMN greeting_events.created_at          IS 'Wall-clock timestamp when this greeting was produced. Immutable.';


-- ============================================================
-- TABLE: app_config
-- ============================================================
-- Generic key/value store for application-level settings that are currently
-- hard-coded in the Java source (e.g. the active template key, the output
-- channel, project name/version).  Moving these here enables runtime
-- reconfiguration without recompilation.
-- ============================================================
CREATE TABLE app_config (
    -- ---- identity ----
    config_id     BIGSERIAL     PRIMARY KEY,

    -- Dot-notation key, e.g. 'app.name', 'greeting.template.active_key'.
    config_key    VARCHAR(200)  NOT NULL,

    -- The configuration value as a string; interpret according to config_type.
    config_value  TEXT,

    -- Data type hint:
    --   STRING   — plain text (default)
    --   INTEGER  — parse as whole number
    --   BOOLEAN  — 'true' / 'false'
    --   TEMPLATE — value is a greeting template string
    --   JSON     — value is a JSON document
    config_type   VARCHAR(20)   NOT NULL DEFAULT 'STRING',

    -- Human-readable description of what this setting controls.
    description   TEXT,

    -- Soft-delete flag.
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,

    -- Protects seed rows from accidental deletion.
    is_system     BOOLEAN       NOT NULL DEFAULT FALSE,

    -- ---- audit ----
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- ---- constraints ----
    CONSTRAINT uq_app_config_key
        UNIQUE (config_key),

    CONSTRAINT chk_app_config_type
        CHECK (config_type IN ('STRING', 'INTEGER', 'BOOLEAN', 'TEMPLATE', 'JSON'))
);

-- Indexes for app_config
CREATE INDEX idx_app_config_key        ON app_config (config_key);
CREATE INDEX idx_app_config_active     ON app_config (is_active);
CREATE INDEX idx_app_config_type       ON app_config (config_type);

-- Table/column comments
COMMENT ON TABLE  app_config IS
    'Key/value store for application configuration settings. '
    'Externalises values currently hard-coded in GreetingRepository and HelloWorld.';

COMMENT ON COLUMN app_config.config_id    IS 'Surrogate primary key — auto-incremented.';
COMMENT ON COLUMN app_config.config_key   IS 'Unique dot-notation key, e.g. ''app.name'', ''greeting.template.active_key''.';
COMMENT ON COLUMN app_config.config_value IS 'Setting value as a string; interpret according to config_type.';
COMMENT ON COLUMN app_config.config_type  IS 'Type hint: STRING, INTEGER, BOOLEAN, TEMPLATE, or JSON.';
COMMENT ON COLUMN app_config.description  IS 'Human-readable explanation of this configuration setting.';
COMMENT ON COLUMN app_config.is_active    IS 'FALSE = setting is disabled; application uses compiled-in default instead.';
COMMENT ON COLUMN app_config.is_system    IS 'TRUE = installed at schema init time; protected from deletion by application logic.';
COMMENT ON COLUMN app_config.created_at   IS 'Wall-clock timestamp when this row was inserted.';
COMMENT ON COLUMN app_config.updated_at   IS 'Wall-clock timestamp of the most recent UPDATE; maintained by trigger trg_app_config_updated_at.';

-- Auto-update trigger
CREATE TRIGGER trg_app_config_updated_at
    BEFORE UPDATE ON app_config
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();


-- ============================================================
-- VIEWS
-- ============================================================

-- View: active templates available for use
CREATE OR REPLACE VIEW v_active_greeting_templates AS
SELECT
    template_id,
    template_key,
    template_value,
    placeholder_count,
    description,
    is_system,
    created_at
FROM greeting_templates
WHERE is_active = TRUE;

COMMENT ON VIEW v_active_greeting_templates IS
    'Active greeting templates available for use by GreetingService. '
    'Excludes soft-deleted (is_active = FALSE) rows.';

-- View: the current default recipient (BR-008, BR-009, BR-013)
CREATE OR REPLACE VIEW v_default_recipient AS
SELECT
    recipient_id,
    recipient_name,
    COALESCE(display_name, recipient_name) AS display_name,
    source,
    created_at
FROM recipients
WHERE is_default = TRUE
  AND is_active  = TRUE;

COMMENT ON VIEW v_default_recipient IS
    'The single active default recipient (BR-013: ''World''). '
    'Used by GreetingService.createGreeting() when requested_recipient is null or blank.';

-- View: denormalised event summary for dashboards
CREATE OR REPLACE VIEW v_greeting_event_summary AS
SELECT
    ge.event_id,
    ge.created_at,
    gt.template_key,
    gt.template_value,
    ge.requested_recipient,
    ge.args_count,
    ge.resolved_recipient,
    ge.resolution_strategy,
    ge.workflow_id,
    ge.generated_greeting,
    ge.output_channel,
    r.recipient_name      AS catalogued_recipient_name,
    r.is_default          AS recipient_is_default
FROM greeting_events  ge
JOIN  greeting_templates gt ON gt.template_id = ge.template_id
LEFT JOIN recipients   r   ON r.recipient_id  = ge.recipient_id;

COMMENT ON VIEW v_greeting_event_summary IS
    'Denormalised view of greeting_events joined to greeting_templates and recipients. '
    'Intended for dashboards, analytics queries, and audit reports.';

-- View: workflow invocation statistics
CREATE OR REPLACE VIEW v_workflow_statistics AS
SELECT
    resolution_strategy,
    workflow_id,
    COUNT(*)                          AS event_count,
    MIN(created_at)                   AS first_event_at,
    MAX(created_at)                   AS last_event_at,
    ROUND(
        COUNT(*) * 100.0 /
        NULLIF(SUM(COUNT(*)) OVER (), 0),
    2)                                AS percentage
FROM greeting_events
GROUP BY resolution_strategy, workflow_id
ORDER BY event_count DESC;

COMMENT ON VIEW v_workflow_statistics IS
    'Aggregated greeting event counts by resolution strategy and workflow, '
    'with percentage of total events. Maps to BR-001/BR-008/BR-009 invocation rates.';


-- ============================================================
-- SEED DATA — Default / initial rows
-- ============================================================
-- Establishes the canonical initial state that mirrors the current hard-coded
-- behaviour of GreetingRepository.  All seed rows are flagged is_system = TRUE.

-- ------------------------------------------------------------
-- Seed: greeting_templates  (BR-012, BR-014)
-- ------------------------------------------------------------
INSERT INTO greeting_templates
    (template_key, template_value, placeholder_count, description, is_active, is_system)
VALUES
    (
        'DEFAULT_HELLO',
        'Hello %s',
        1,
        'Default greeting template. Produces output of the form "Hello <recipient>". '
        'Mirrors GreetingRepository.getGreetingTemplate() (BR-012).',
        TRUE,
        TRUE
    ),
    (
        'INFORMAL_HI',
        'Hi %s',
        1,
        'Informal greeting variant. Inactive by default; activate to replace DEFAULT_HELLO.',
        FALSE,
        FALSE
    ),
    (
        'FORMAL_DEAR',
        'Dear %s',
        1,
        'Formal greeting variant suitable for correspondence. Inactive by default.',
        FALSE,
        FALSE
    ),
    (
        'FAREWELL',
        'Goodbye %s',
        1,
        'Farewell message template. Inactive by default.',
        FALSE,
        FALSE
    );

-- ------------------------------------------------------------
-- Seed: recipients  (BR-013, BR-010)
-- ------------------------------------------------------------
INSERT INTO recipients
    (recipient_name, display_name, is_default, source, is_active)
VALUES
    (
        'World',
        'World',
        TRUE,      -- BR-013: 'World' is the default recipient
        'SYSTEM',
        TRUE
    ),
    (
        'Copilot',
        'GitHub Copilot',
        FALSE,     -- Non-default; used in HelloWorldTest.controllerUsesFirstArgumentAsRecipient
        'SYSTEM',
        TRUE
    );

-- ------------------------------------------------------------
-- Seed: app_config — externalises hard-coded settings
-- ------------------------------------------------------------
INSERT INTO app_config
    (config_key, config_value, config_type, description, is_active, is_system)
VALUES
    (
        'app.name',
        'LegacyFinApp-026',
        'STRING',
        'Application display name (Maven artifact hello-world, project LegacyFinApp-026).',
        TRUE, TRUE
    ),
    (
        'app.version',
        '1.0.0',
        'STRING',
        'Application version, mirrors <version> in pom.xml.',
        TRUE, TRUE
    ),
    (
        'app.group_id',
        'com.example',
        'STRING',
        'Maven group identifier.',
        TRUE, TRUE
    ),
    (
        'greeting.template.active_key',
        'DEFAULT_HELLO',
        'STRING',
        'template_key of the active greeting template for GreetingRepository to load. '
        'Change to switch templates without redeployment (BR-012).',
        TRUE, TRUE
    ),
    (
        'greeting.default.output_channel',
        'STDOUT',
        'STRING',
        'Channel to which generated greetings are written (BR-002). '
        'Extend to support FILE, DATABASE, API.',
        TRUE, TRUE
    ),
    (
        'greeting.recipient.trim_enabled',
        'true',
        'BOOLEAN',
        'When true, GreetingService trims whitespace from requested recipient (BR-010).',
        TRUE, TRUE
    ),
    (
        'greeting.recipient.fallback_on_blank',
        'true',
        'BOOLEAN',
        'When true, a blank recipient triggers fallback to default recipient (BR-009).',
        TRUE, TRUE
    ),
    (
        'greeting.args.use_first_only',
        'true',
        'BOOLEAN',
        'When true, only args[0] is used as recipient; later arguments are discarded (BR-006).',
        TRUE, TRUE
    );

-- ------------------------------------------------------------
-- Seed: greeting_events — canonical WF-001 "Hello World" event
-- Corresponds to HelloWorldTest.mainPrintsHelloWorldWithTrailingNewline
-- ------------------------------------------------------------
INSERT INTO greeting_events
    (
        template_id,
        recipient_id,
        requested_recipient,
        args_count,
        resolved_recipient,
        resolution_strategy,
        workflow_id,
        generated_greeting,
        output_channel
    )
SELECT
    gt.template_id,
    r.recipient_id,
    NULL,            -- no CLI argument supplied (BR-005)
    0,               -- empty args array (BR-005)
    'World',         -- default recipient resolved (BR-013)
    'DEFAULT_USED',  -- WF-001 path (BR-001, BR-008)
    'WF-001',
    'Hello World',   -- BR-012 + BR-013
    'STDOUT'         -- BR-002
FROM greeting_templates gt
CROSS JOIN recipients r
WHERE gt.template_key = 'DEFAULT_HELLO'
  AND r.recipient_name = 'World'
  AND r.is_default = TRUE;


-- ============================================================
-- END OF SCHEMA
-- ============================================================
-- Summary statistics:
--   Tables   : 4   (greeting_templates, recipients, greeting_events, app_config)
--   Columns  : 43  total across all tables
--   Indexes  : 17  (14 regular + 1 partial unique + 2 partial composite)
--   FK refs  : 2   (greeting_events → greeting_templates, → recipients)
--   CHK const: 11  across all tables
--   UNIQUE   : 3   (template_key, config_key, single_default)
--   Triggers : 3   (updated_at on greeting_templates, recipients, app_config)
--   Views    : 4   (v_active_greeting_templates, v_default_recipient,
--                   v_greeting_event_summary, v_workflow_statistics)
--   Seed rows: 15  (4 templates + 2 recipients + 8 app_config + 1 greeting_event)
--
-- Business rules fully covered by schema elements:
--   BR-001 (default args)  → resolution_strategy = 'DEFAULT_USED', workflow_id = 'WF-001'
--   BR-002 (stdout output) → output_channel DEFAULT 'STDOUT', CHECK constraint
--   BR-004 (null args)     → requested_recipient nullable column
--   BR-005 (empty args)    → args_count = 0 seed, CHECK args_count >= 0
--   BR-006 (first arg)     → single requested_recipient column
--   BR-008 (null fallback) → resolution_strategy = 'DEFAULT_USED'
--   BR-009 (blank fallback)→ resolution_strategy = 'BLANK_FALLBACK', consistency CHECK
--   BR-010 (trim)          → chk_recipients_name_not_blank, column comment
--   BR-011 (format)        → generated_greeting NOT NULL, FK to template
--   BR-012 (template)      → seed row 'Hello %s', chk value has placeholder
--   BR-013 (default recip) → seed row 'World' with is_default=TRUE
--   BR-014 (one placeholder)→ chk_placeholder_count = 1, chk value has %s
-- ============================================================
