# generated by AI in Github cloud
from __future__ import annotations

import platform
from dataclasses import dataclass
from datetime import date


# generated by AI in Github cloud
@dataclass(frozen=True)
class Greeting:
    recipient: str
    message: str

    def __post_init__(self) -> None:
        if self.recipient is None or not self.recipient.strip():
            raise ValueError("recipient must not be blank")
        if self.message is None or not self.message.strip():
            raise ValueError("message must not be blank")

    def formatted(self) -> str:
        return (
            "╔══════════════════════════════╗\n"
            f"║  {self.message}, {self.recipient}!  ║\n"
            "╚══════════════════════════════╝\n"
        )


def salutation_for_hour(hour: int) -> str:
    if hour < 12:
        return "Good morning"
    if hour < 17:
        return "Good afternoon"
    return "Good evening"


def season_of(month: int) -> str:
    if month in (12, 1, 2):
        return "Winter"
    if month in (3, 4, 5):
        return "Spring"
    if month in (6, 7, 8):
        return "Summer"
    if month in (9, 10, 11):
        return "Autumn"
    raise ValueError("month must be in 1..12")


def build_output(today: date | None = None, python_version: str | None = None) -> str:
    current_day = today or date.today()
    version = python_version or platform.python_version()
    greeting = Greeting("World", salutation_for_hour(current_day.day % 24))
    return (
        f"{greeting.formatted()}"
        f"Python version : {version}\n"
        f"Today's date : {current_day.isoformat()} ({season_of(current_day.month)})\n"
    )


def main() -> None:
    print(build_output(), end="")


if __name__ == "__main__":
    main()
