// generated by AI in Github cloud
import java.time.LocalDate;
import java.time.Month;

/**
 * Hello World application modernized for Java 25.
 *
 * <p>Demonstrates modern Java features:
 * <ul>
 *   <li>Records (Java 16+)</li>
 *   <li>Text blocks (Java 15+)</li>
 *   <li>Local-variable type inference via {@code var} (Java 10+)</li>
 *   <li>Switch expressions (Java 14+)</li>
 *   <li>Sealed interfaces &amp; pattern matching (Java 21+, current in Java 25)</li>
 * </ul>
 */
public class HelloWorld {

    /** Immutable value object holding a greeting message – uses a Java 16 record. */
    record Greeting(String recipient, String message) {

        /** Compact canonical constructor – validates inputs. */
        Greeting {
            if (recipient == null || recipient.isBlank()) {
                throw new IllegalArgumentException("recipient must not be blank");
            }
            if (message == null || message.isBlank()) {
                throw new IllegalArgumentException("message must not be blank");
            }
        }

        /** Returns a fully-formatted greeting string using a Java 15 text block. */
        String formatted() {
            return """
                    ╔══════════════════════════════╗
                    ║  %s, %s!  ║
                    ╚══════════════════════════════╝
                    """.formatted(message, recipient);
        }
    }

    /** Simple sealed hierarchy used to show modern pattern matching in Java 25. */
    sealed interface TimeOfDay permits TimeOfDay.Morning, TimeOfDay.Afternoon, TimeOfDay.Evening {
        record Morning() implements TimeOfDay {}
        record Afternoon() implements TimeOfDay {}
        record Evening() implements TimeOfDay {}

        /** Factory – maps an hour (0-23) to the appropriate {@link TimeOfDay}. */
        static TimeOfDay of(int hour) {
            // Box to Integer so the switch can use guarded pattern matching in Java 25
            return switch ((Integer) hour) {
                case Integer h when h < 12 -> new Morning();
                case Integer h when h < 17 -> new Afternoon();
                default                    -> new Evening();
            };
        }
    }

    public static void main(String[] args) {
        // var – local-variable type inference (Java 10+)
        var today = LocalDate.now();

        // Switch expression with pattern matching in Java 25
        var timeOfDay = TimeOfDay.of(today.getDayOfMonth() % 24);
        var salutation = switch (timeOfDay) {
            case TimeOfDay.Morning   ignored -> "Good morning";
            case TimeOfDay.Afternoon ignored -> "Good afternoon";
            case TimeOfDay.Evening   ignored -> "Good evening";
        };

        var greeting = new Greeting("World", salutation);

        // Text block output
        System.out.print(greeting.formatted());

        // Multi-line text block with runtime values interpolated via formatted()
        var info = """
                Java version : %s
                Today's date : %s (%s)
                """.formatted(
                System.getProperty("java.version"),
                today,
                seasonOf(today.getMonth()));

        System.out.print(info);
    }

    /** Returns the meteorological season for the given {@link Month}. */
    static String seasonOf(Month month) {
        return switch (month) {
            case DECEMBER, JANUARY, FEBRUARY -> "Winter";
            case MARCH, APRIL, MAY           -> "Spring";
            case JUNE, JULY, AUGUST          -> "Summer";
            case SEPTEMBER, OCTOBER, NOVEMBER -> "Autumn";
        };
    }
}
