# generated by AI in Github cloud
"""Hello World application – Python port of HelloWorld.java.

Demonstrates idiomatic Python 3 equivalents of modern Java features:
  - dataclass  (≈ Java record)
  - enum / plain classes  (≈ sealed interface hierarchy)
  - match/case or dict lookup  (≈ switch expression)
  - f-strings / multi-line strings  (≈ text blocks)
"""

import sys
import datetime
from dataclasses import dataclass


# ---------------------------------------------------------------------------
# Greeting  (≈ Java record Greeting)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Greeting:
    """Immutable value object holding a greeting message."""

    recipient: str
    message: str

    def __post_init__(self):
        if not self.recipient or not self.recipient.strip():
            raise ValueError("recipient must not be blank")
        if not self.message or not self.message.strip():
            raise ValueError("message must not be blank")

    def formatted(self) -> str:
        """Return a fully-formatted greeting string."""
        return (
            "╔══════════════════════════════╗\n"
            f"║  {self.message}, {self.recipient}!  ║\n"
            "╚══════════════════════════════╝\n"
        )


# ---------------------------------------------------------------------------
# TimeOfDay  (≈ Java sealed interface TimeOfDay)
# ---------------------------------------------------------------------------

class TimeOfDay:
    """Namespace for the time-of-day hierarchy."""

    class Morning:
        pass

    class Afternoon:
        pass

    class Evening:
        pass

    @staticmethod
    def of(hour: int) -> object:
        """Map an hour (0-23) to the appropriate TimeOfDay instance."""
        if hour < 12:
            return TimeOfDay.Morning()
        elif hour < 17:
            return TimeOfDay.Afternoon()
        else:
            return TimeOfDay.Evening()


# ---------------------------------------------------------------------------
# seasonOf  (≈ Java static String seasonOf(Month month))
# ---------------------------------------------------------------------------

_SEASON_MAP = {
    12: "Winter", 1: "Winter",  2: "Winter",
     3: "Spring", 4: "Spring",  5: "Spring",
     6: "Summer", 7: "Summer",  8: "Summer",
     9: "Autumn", 10: "Autumn", 11: "Autumn",
}


def season_of(month: int) -> str:
    """Return the meteorological season for the given month number (1-12)."""
    return _SEASON_MAP[month]


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main():
    today = datetime.date.today()

    time_of_day = TimeOfDay.of(today.day % 24)

    if isinstance(time_of_day, TimeOfDay.Morning):
        salutation = "Good morning"
    elif isinstance(time_of_day, TimeOfDay.Afternoon):
        salutation = "Good afternoon"
    else:
        salutation = "Good evening"

    greeting = Greeting("World", salutation)
    print(greeting.formatted(), end="")

    info = (
        f"Python version : {sys.version}\n"
        f"Today's date   : {today} ({season_of(today.month)})\n"
    )
    print(info, end="")


if __name__ == "__main__":
    main()
