# generated by AI in Github cloud
from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from enum import Enum
import platform
import sys


@dataclass(frozen=True)
# generated by AI in Github cloud
class Greeting:
    recipient: str
    message: str

    def __post_init__(self) -> None:
        if not self.recipient or not self.recipient.strip():
            raise ValueError("recipient must not be blank")
        if not self.message or not self.message.strip():
            raise ValueError("message must not be blank")

    def formatted(self) -> str:
        return (
            "╔══════════════════════════════╗\n"
            f"║  {self.message}, {self.recipient}!  ║\n"
            "╚══════════════════════════════╝\n"
        )


# generated by AI in Github cloud
class TimeOfDay:
    @staticmethod
    def of(hour: int) -> "TimeOfDay":
        if hour < 12:
            return Morning()
        if hour < 17:
            return Afternoon()
        return Evening()


# generated by AI in Github cloud
class Morning(TimeOfDay):
    pass


# generated by AI in Github cloud
class Afternoon(TimeOfDay):
    pass


# generated by AI in Github cloud
class Evening(TimeOfDay):
    pass


# generated by AI in Github cloud
class Month(Enum):
    JANUARY = 1
    FEBRUARY = 2
    MARCH = 3
    APRIL = 4
    MAY = 5
    JUNE = 6
    JULY = 7
    AUGUST = 8
    SEPTEMBER = 9
    OCTOBER = 10
    NOVEMBER = 11
    DECEMBER = 12


def season_of(month: Month) -> str:
    if month in (Month.DECEMBER, Month.JANUARY, Month.FEBRUARY):
        return "Winter"
    if month in (Month.MARCH, Month.APRIL, Month.MAY):
        return "Spring"
    if month in (Month.JUNE, Month.JULY, Month.AUGUST):
        return "Summer"
    return "Autumn"


def build_output(today: date | None = None, python_version: str | None = None) -> str:
    today = today or date.today()
    time_of_day = TimeOfDay.of(today.day % 24)

    if isinstance(time_of_day, Morning):
        salutation = "Good morning"
    elif isinstance(time_of_day, Afternoon):
        salutation = "Good afternoon"
    else:
        salutation = "Good evening"

    greeting = Greeting("World", salutation)
    version = python_version or platform.python_version()
    month = Month(today.month)

    return (
        greeting.formatted()
        + f"Python version : {version}\n"
        + f"Today's date : {today} ({season_of(month)})\n"
    )


def main() -> None:
    sys.stdout.write(build_output())


if __name__ == "__main__":
    main()
