# generated by AI in Github cloud
from setuptools import setup, find_packages

setup(
    name="hello-world",
    version="1.0.0",
    packages=find_packages(where="."),
    python_requires=">=3.10",
    extras_require={
        "test": ["pytest>=7.0"],
    },
)
