# generated by AI in Github cloud
"""Package setup for the Hello World Python application."""

from setuptools import setup, find_packages

setup(
    name="hello-world",
    version="1.0.0",
    description="Hello World application migrated from Java 21 to Python",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    python_requires=">=3.9",
    extras_require={
        "test": [
            "pytest>=7.0",
        ],
    },
)
