package com.example.helloworld;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for the {@link Greeting} record.
 */
@DisplayName("Greeting record")
class GreetingTest {

    // -----------------------------------------------------------------------
    // Construction
    // -----------------------------------------------------------------------

    @Test
    @DisplayName("hello() factory creates a greeting with the correct recipient and message")
    void helloFactory_setsFields() {
        var greeting = Greeting.hello("World");

        assertEquals("World", greeting.recipient());
        assertEquals("Hello, World!", greeting.message());
    }

    @Test
    @DisplayName("canonical constructor strips leading/trailing whitespace")
    void constructor_stripsWhitespace() {
        var greeting = new Greeting("  Alice  ", "  Hi there!  ");

        assertEquals("Alice", greeting.recipient());
        assertEquals("Hi there!", greeting.message());
    }

    @ParameterizedTest
    @ValueSource(strings = {"", "   ", "\t"})
    @DisplayName("constructor throws when recipient is blank")
    void constructor_rejectsBlankRecipient(String blank) {
        assertThrows(IllegalArgumentException.class,
                () -> new Greeting(blank, "Hello!"));
    }

    @ParameterizedTest
    @ValueSource(strings = {"", "   ", "\t"})
    @DisplayName("constructor throws when message is blank")
    void constructor_rejectsBlankMessage(String blank) {
        assertThrows(IllegalArgumentException.class,
                () -> new Greeting("World", blank));
    }

    @Test
    @DisplayName("constructor throws when recipient is null")
    void constructor_rejectsNullRecipient() {
        assertThrows(IllegalArgumentException.class,
                () -> new Greeting(null, "Hello!"));
    }

    @Test
    @DisplayName("constructor throws when message is null")
    void constructor_rejectsNullMessage() {
        assertThrows(IllegalArgumentException.class,
                () -> new Greeting("World", null));
    }

    // -----------------------------------------------------------------------
    // format()
    // -----------------------------------------------------------------------

    @Test
    @DisplayName("format() output contains the greeting message")
    void format_containsMessage() {
        var greeting = Greeting.hello("Java 21");

        String formatted = greeting.format();

        assertTrue(formatted.contains("Hello, Java 21!"),
                "Formatted output should contain the greeting message");
    }

    @Test
    @DisplayName("format() output uses text-block style box characters")
    void format_containsBoxCharacters() {
        var greeting = Greeting.hello("Test");

        String formatted = greeting.format();

        assertTrue(formatted.contains("┌"), "Should have top-left box corner");
        assertTrue(formatted.contains("└"), "Should have bottom-left box corner");
    }

    // -----------------------------------------------------------------------
    // Record equality & identity (auto-generated by the record)
    // -----------------------------------------------------------------------

    @Test
    @DisplayName("two Greetings with identical fields are equal")
    void recordEquality() {
        var g1 = new Greeting("World", "Hello, World!");
        var g2 = new Greeting("World", "Hello, World!");

        assertEquals(g1, g2);
        assertEquals(g1.hashCode(), g2.hashCode());
    }

    @Test
    @DisplayName("toString() contains both fields")
    void recordToString() {
        var greeting = new Greeting("World", "Hello, World!");
        String str = greeting.toString();

        assertTrue(str.contains("World"));
        assertTrue(str.contains("Hello, World!"));
    }
}
