# generated by AI in Github cloud
"""Python unittest port of HelloWorldTest.java.

Covers every test case from the original JUnit 5 suite:
  - Greeting dataclass stores fields
  - Greeting formatted output contains recipient and message
  - Greeting rejects blank recipient
  - Greeting rejects blank message
  - TimeOfDay.Morning  for hour < 12
  - TimeOfDay.Afternoon for hour 12-16
  - TimeOfDay.Evening  for hour 17+
  - season_of for all 12 months
"""

import sys
import os
import unittest

# Allow running from repo root OR from tests/ directory
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from hello_world import Greeting, TimeOfDay, season_of


class TestGreeting(unittest.TestCase):
    """Tests for the Greeting dataclass."""

    def test_greeting_record_stores_fields(self):
        """Greeting dataclass stores recipient and message."""
        g = Greeting("World", "Hello")
        self.assertEqual("World", g.recipient)
        self.assertEqual("Hello", g.message)

    def test_greeting_formatted_contains_recipient_and_message(self):
        """formatted() output contains the recipient and message."""
        g = Greeting("Alice", "Hi")
        result = g.formatted()
        self.assertIn("Alice", result, "formatted output should contain recipient")
        self.assertIn("Hi", result, "formatted output should contain message")

    def test_greeting_rejects_blank_recipient(self):
        """Greeting raises ValueError when recipient is blank."""
        with self.assertRaises(ValueError):
            Greeting("", "Hello")

    def test_greeting_rejects_blank_message(self):
        """Greeting raises ValueError when message is blank (whitespace only)."""
        with self.assertRaises(ValueError):
            Greeting("World", "  ")


class TestTimeOfDay(unittest.TestCase):
    """Tests for the TimeOfDay hierarchy."""

    def test_time_of_day_morning_for_hour_less_than_12(self):
        """Hours 0 and 11 map to Morning."""
        self.assertIsInstance(TimeOfDay.of(0),  TimeOfDay.Morning)
        self.assertIsInstance(TimeOfDay.of(11), TimeOfDay.Morning)

    def test_time_of_day_afternoon_for_hour_12_to_16(self):
        """Hours 12 and 16 map to Afternoon."""
        self.assertIsInstance(TimeOfDay.of(12), TimeOfDay.Afternoon)
        self.assertIsInstance(TimeOfDay.of(16), TimeOfDay.Afternoon)

    def test_time_of_day_evening_for_hour_17_and_above(self):
        """Hours 17 and 23 map to Evening."""
        self.assertIsInstance(TimeOfDay.of(17), TimeOfDay.Evening)
        self.assertIsInstance(TimeOfDay.of(23), TimeOfDay.Evening)


class TestSeasonOf(unittest.TestCase):
    """Tests for season_of – one sub-test per month (mirrors @CsvSource)."""

    _CASES = [
        (12, "Winter"),
        (1,  "Winter"),
        (2,  "Winter"),
        (3,  "Spring"),
        (4,  "Spring"),
        (5,  "Spring"),
        (6,  "Summer"),
        (7,  "Summer"),
        (8,  "Summer"),
        (9,  "Autumn"),
        (10, "Autumn"),
        (11, "Autumn"),
    ]

    def test_season_of_returns_correct_season(self):
        """season_of returns the correct meteorological season for every month."""
        for month, expected in self._CASES:
            with self.subTest(month=month):
                self.assertEqual(expected, season_of(month))


if __name__ == "__main__":
    unittest.main()
