# generated by AI in Github cloud
import io
import unittest
from contextlib import redirect_stdout
from datetime import date
from unittest.mock import patch

import hello_world


# generated by AI in Github cloud
class HelloWorldTest(unittest.TestCase):
    def test_greeting_stores_fields(self) -> None:
        greeting = hello_world.Greeting("World", "Hello")
        self.assertEqual("World", greeting.recipient)
        self.assertEqual("Hello", greeting.message)

    def test_greeting_formatted_contains_recipient_and_message(self) -> None:
        result = hello_world.Greeting("Alice", "Hi").formatted()
        self.assertIn("Alice", result)
        self.assertIn("Hi", result)

    def test_greeting_rejects_blank_recipient(self) -> None:
        with self.assertRaises(ValueError):
            hello_world.Greeting("", "Hello")

    def test_greeting_rejects_blank_message(self) -> None:
        with self.assertRaises(ValueError):
            hello_world.Greeting("World", "  ")

    def test_salutation_for_morning_hours(self) -> None:
        self.assertEqual("Good morning", hello_world.salutation_for_hour(0))
        self.assertEqual("Good morning", hello_world.salutation_for_hour(11))

    def test_salutation_for_afternoon_hours(self) -> None:
        self.assertEqual("Good afternoon", hello_world.salutation_for_hour(12))
        self.assertEqual("Good afternoon", hello_world.salutation_for_hour(16))

    def test_salutation_for_evening_hours(self) -> None:
        self.assertEqual("Good evening", hello_world.salutation_for_hour(17))
        self.assertEqual("Good evening", hello_world.salutation_for_hour(23))

    def test_season_of_returns_correct_season(self) -> None:
        expectations = {
            12: "Winter",
            1: "Winter",
            2: "Winter",
            3: "Spring",
            4: "Spring",
            5: "Spring",
            6: "Summer",
            7: "Summer",
            8: "Summer",
            9: "Autumn",
            10: "Autumn",
            11: "Autumn",
        }
        for month, expected in expectations.items():
            with self.subTest(month=month):
                self.assertEqual(expected, hello_world.season_of(month))

    def test_build_output_uses_expected_format(self) -> None:
        result = hello_world.build_output(date(2026, 5, 19), "3.13.3")
        self.assertEqual(
            "╔══════════════════════════════╗\n"
            "║  Good evening, World!  ║\n"
            "╚══════════════════════════════╝\n"
            "Python version : 3.13.3\n"
            "Today's date : 2026-05-19 (Spring)\n",
            result,
        )

    def test_main_prints_built_output(self) -> None:
        buffer = io.StringIO()
        with patch("hello_world.build_output", return_value="rendered\n"), redirect_stdout(buffer):
            hello_world.main()
        self.assertEqual("rendered\n", buffer.getvalue())


if __name__ == "__main__":
    unittest.main()
