#!/usr/bin/env python3
"""
Portfolio modernization analysis - Steps 2-7
generated by AI in Github cloud
"""

import json
import os
import math
from datetime import datetime

BASE = "/home/runner/work/copilot-test-ktruchcz/copilot-test-ktruchcz"
INPUT_DIR = os.path.join(BASE, "discover/output/applications/internal_app_model")
OUTPUT_DIR = os.path.join(BASE, "discover/output")
COMMENT = "generated by AI in Github cloud"
TIMESTAMP = "2025-01-15T00:00:00Z"

RETIRED_IDS = {"app005", "app007", "app009", "app029"}
ALL_IDS = [f"app{str(i).zfill(3)}" for i in range(1, 31)]
IN_SCOPE_IDS = [a for a in ALL_IDS if a not in RETIRED_IDS]

# ─── Load all apps ────────────────────────────────────────────────────────────
def load_apps():
    apps = {}
    for aid in ALL_IDS:
        path = os.path.join(INPUT_DIR, f"{aid}.json")
        with open(path) as f:
            apps[aid] = json.load(f)
    return apps

# ─── STEP 2: Out-of-scope ─────────────────────────────────────────────────────
def step2_out_of_scope(apps):
    out_dir = os.path.join(OUTPUT_DIR, "out_of_scope_results")
    os.makedirs(out_dir, exist_ok=True)
    for aid, app in apps.items():
        status = app.get("application_status", "")
        decomm = str(app.get("additional_attributes", {}).get("decomission_date", ""))
        retired = status.lower() == "retired" or decomm.lower() == "already retired"
        sap_check = "sap" in app.get("app_name", "").lower() or "sap" in app.get("app_description", "").lower()
        result = {
            "_comment": COMMENT,
            "application_identifier": aid,
            "assessments": [
                {
                    "exclusion_type": "RETIRED",
                    "applies": retired,
                    "confidence": 9,
                    "reasoning": f"Application status is '{status}'." + (f" Decommission date: '{decomm}'." if retired else "")
                },
                {
                    "exclusion_type": "SAP",
                    "applies": sap_check,
                    "confidence": 9,
                    "reasoning": "SAP indicators detected." if sap_check else "No SAP indicators found."
                }
            ],
            "out_of_scope": retired or sap_check
        }
        with open(os.path.join(out_dir, f"out_of_scope_{aid}.json"), "w") as f:
            json.dump(result, f, indent=2)
    print(f"  Step 2: {len(apps)} out-of-scope files written.")

# ─── Tech lifecycle knowledge ─────────────────────────────────────────────────
OS_STATUS = {
    "AIX 7.2": ("OUTDATED", "AIX 7.2 full support ended November 2023; limited extended support.", "2023-11-30"),
    "AIX 6": ("EOL", "AIX 6 end of support was 2015.", "2015-04-30"),
    "RHEL 7": ("EOL", "RHEL 7 maintenance support ended June 2024.", "2024-06-30"),
    "RHEL 8": ("CURRENT_VERSION", "RHEL 8 supported until May 2029.", "2029-05-31"),
    "Debian 6": ("EOL", "Debian 6 end of support February 2016.", "2016-02-29"),
    "Debian 7": ("EOL", "Debian 7 end of support May 2018.", "2018-05-31"),
    "Windows Server 2012": ("EOL", "Windows Server 2012 end of support October 2023.", "2023-10-10"),
    "Windows Server 2019": ("CURRENT_VERSION", "Windows Server 2019 supported until January 2029.", "2029-01-09"),
    "Windows Server 2022": ("CURRENT_VERSION", "Windows Server 2022 supported until October 2031.", "2031-10-14"),
    "CentOS 7": ("EOL", "CentOS 7 end of support June 2024.", "2024-06-30"),
    "Ubuntu 14": ("EOL", "Ubuntu 14.04 end of support April 2019.", "2019-04-30"),
}

LANG_STATUS = {
    "COBOL-2014": ("OUTDATED", "COBOL-2014 is still used but aging, not actively evolved.", None),
    "Java 8": ("OUTDATED", "Java 8 premier support ended March 2022; extended support available.", "2022-03-31"),
    "Java 11": ("CURRENT_VERSION", "Java 11 LTS supported until September 2026.", "2026-09-30"),
    "Java 17": ("CURRENT_VERSION", "Java 17 LTS supported until September 2029.", "2029-09-30"),
    "Python 3.7": ("EOL", "Python 3.7 end of support June 2023.", "2023-06-27"),
    "Python 3.8": ("OUTDATED", "Python 3.8 end of support October 2024; effectively near-EOL.", "2024-10-31"),
    "Python 3.9": ("OUTDATED", "Python 3.9 end of support October 2025.", "2025-10-31"),
    "Python 3.11": ("CURRENT_VERSION", "Python 3.11 supported until October 2027.", "2027-10-31"),
    "Go 1.16": ("OUTDATED", "Go 1.16 is not in the current two major releases as of 2024.", None),
    "Go 1.19": ("OUTDATED", "Go 1.19 is not in the current two major releases as of 2024.", None),
    "Node.js 18": ("CURRENT_VERSION", "Node.js 18 LTS active until April 2025.", "2025-04-30"),
    "Node.js 14": ("EOL", "Node.js 14 reached EOL April 2023.", "2023-04-30"),
    "Ruby 2.7": ("EOL", "Ruby 2.7 end of support March 2023.", "2023-03-31"),
    "PHP 8.1": ("CURRENT_VERSION", "PHP 8.1 security support until November 2025.", "2025-11-25"),
    "C# .NET 6": ("OUTDATED", ".NET 6 reached EOL November 2024.", "2024-11-12"),
    "Angular 15": ("OUTDATED", "Angular 15 reached EOL May 2023.", "2023-05-18"),
    "React Native": ("CURRENT_VERSION", "React Native is actively maintained.", None),
    "ASP.NET Core": ("CURRENT_VERSION", "ASP.NET Core (recent version) actively maintained.", None),
    "VB.NET": ("OUTDATED", "VB.NET on .NET Framework is legacy; limited future investment.", None),
    "Rust 1.70": ("CURRENT_VERSION", "Rust 1.70 is a recent stable release; Rust has rolling releases.", None),
    "Scala 2.13": ("OUTDATED", "Scala 3 is current; Scala 2.13 still maintained but aging.", None),
    "C++ 17": ("CURRENT_VERSION", "C++17 is a current and widely supported standard.", None),
    "PowerShell": ("OUTDATED", "PowerShell version unspecified; assuming OUTDATED without clear version info.", None),
    "FORTRAN 2018": ("OUTDATED", "Fortran 2018 is functional but niche/aging technology.", None),
    "Perl": ("OUTDATED", "Perl is in maintenance mode with limited active development.", None),
}

APP_SERVER_STATUS = {
    "Websphere 7.0": ("EOL", "WebSphere 7.0 end of support April 2019.", "2019-04-30"),
    "Websphere 8.0": ("OUTDATED", "WebSphere 8.0 standard support ended; extended to 2025.", "2025-04-30"),
    "Websphere 8.5": ("OUTDATED", "WebSphere 8.5 extended support until April 2025.", "2025-04-30"),
    "Oracle Weblogic 8.0": ("EOL", "Oracle WebLogic 8.0 EOL since 2008.", "2008-12-31"),
    "Weblogic 9.0": ("EOL", "WebLogic 9.0 EOL since 2011.", "2011-12-31"),
    "Apache Tomcat 6.1": ("EOL", "Apache Tomcat 6.1 EOL since December 2016.", "2016-12-31"),
    "Apache Tomcat 5.3": ("EOL", "Apache Tomcat 5.3 EOL since 2009.", "2009-12-31"),
    "Apache Tomcat 7.4": ("EOL", "Apache Tomcat 7 EOL since March 2021.", "2021-03-31"),
    "Apache Tomcat 8.0": ("EOL", "Apache Tomcat 8.0 EOL since June 2018.", "2018-06-30"),
    "Microsoft IIS 8.0": ("EOL", "IIS 8.0 on Windows Server 2012 reached EOL October 2023.", "2023-10-10"),
    "Microsoft IIS 8.5": ("EOL", "IIS 8.5 on Windows Server 2012 R2 reached EOL October 2023.", "2023-10-10"),
    "Microsoft IIS 10.0": ("CURRENT_VERSION", "IIS 10.0 on Windows Server 2019/2022 actively supported.", None),
    "Glassfish 3.0": ("EOL", "GlassFish 3.0 EOL since 2013.", "2013-12-31"),
    "Glassfish 4.0": ("EOL", "Eclipse GlassFish 4.0 no longer actively maintained.", "2018-12-31"),
    "Glassfish 4.5": ("EOL", "GlassFish 4.5 no longer actively maintained.", "2019-12-31"),
    "Glassfish 5.0": ("OUTDATED", "Eclipse GlassFish 5 aging; GlassFish 7 is current.", "2026-12-31"),
    "Payara 4.0": ("EOL", "Payara 4 reached EOL June 2023.", "2023-06-30"),
    "Payara 5.0": ("OUTDATED", "Payara 5 reached EOL March 2024.", "2024-03-31"),
    "Payara 6.0": ("CURRENT_VERSION", "Payara 6 is current community version.", None),
}

DB_STATUS = {
    "Oracle 19c": ("CURRENT_VERSION", "Oracle 19c extended support until April 2027.", "2027-04-30"),
    "Oracle 12c": ("OUTDATED", "Oracle 12c extended support ended July 2022; effectively EOL.", "2022-07-31"),
    "Oracle 11g": ("EOL", "Oracle 11g end of support December 2020.", "2020-12-31"),
    "Amazon RDS MySQL": ("CURRENT_VERSION", "Amazon RDS MySQL is a managed service, continuously updated.", None),
    "MySQL 5.7": ("EOL", "MySQL 5.7 end of support October 2023.", "2023-10-31"),
    "MySQL 8.0": ("CURRENT_VERSION", "MySQL 8.0 supported until April 2026.", "2026-04-30"),
    "PostgreSQL 13": ("OUTDATED", "PostgreSQL 13 EOL November 2025; approaching end of life.", "2025-11-13"),
    "PostgreSQL 14": ("CURRENT_VERSION", "PostgreSQL 14 EOL November 2026.", "2026-11-12"),
    "PostgreSQL 15": ("CURRENT_VERSION", "PostgreSQL 15 EOL November 2027.", "2027-11-13"),
    "SQL Server 2014": ("EOL", "SQL Server 2014 end of extended support July 2024.", "2024-07-09"),
    "SQL Server 2016": ("OUTDATED", "SQL Server 2016 extended support until July 2026.", "2026-07-14"),
    "SQL Server 2019": ("CURRENT_VERSION", "SQL Server 2019 extended support until January 2030.", "2030-01-08"),
    "SQL Server 2022": ("CURRENT_VERSION", "SQL Server 2022 mainstream support until January 2028.", "2028-01-11"),
    "MongoDB": ("CURRENT_VERSION", "MongoDB (current version) actively maintained.", None),
    "Aurora PostgreSQL": ("CURRENT_VERSION", "Aurora PostgreSQL is a managed AWS service.", None),
    "DB2": ("OUTDATED", "IBM DB2 LUW still supported but aging; no specific version specified.", None),
}

def get_tech_components(app):
    components = []
    os_val = app.get("operating_system", "")
    lang_val = app.get("programming_language", "")
    server_val = app.get("application_server")
    db_val = app.get("database_engine", "")

    if os_val and os_val in OS_STATUS:
        s, r, eol = OS_STATUS[os_val]
        components.append({
            "component_name": os_val.split()[0],
            "component_family": os_val.split()[0],
            "component_type": "os",
            "managed_service": False,
            "version": " ".join(os_val.split()[1:]) if len(os_val.split()) > 1 else "",
            "component_status": s,
            "eol_date": eol,
            "reason": r,
            "confidence": 8
        })
    
    if lang_val and lang_val in LANG_STATUS:
        s, r, eol = LANG_STATUS[lang_val]
        components.append({
            "component_name": lang_val,
            "component_family": lang_val.split()[0],
            "component_type": "programming_language",
            "managed_service": False,
            "version": lang_val.split()[-1] if len(lang_val.split()) > 1 else "",
            "component_status": s,
            "eol_date": eol,
            "reason": r,
            "confidence": 8
        })

    if server_val and server_val in APP_SERVER_STATUS:
        s, r, eol = APP_SERVER_STATUS[server_val]
        components.append({
            "component_name": server_val,
            "component_family": server_val.split()[0],
            "component_type": "application_server",
            "managed_service": False,
            "version": server_val.split()[-1] if len(server_val.split()) > 1 else "",
            "component_status": s,
            "eol_date": eol,
            "reason": r,
            "confidence": 8
        })

    if db_val and db_val in DB_STATUS:
        s, r, eol = DB_STATUS[db_val]
        is_managed = db_val in ("Amazon RDS MySQL", "Aurora PostgreSQL")
        components.append({
            "component_name": db_val,
            "component_family": db_val.split()[0],
            "component_type": "database",
            "managed_service": is_managed,
            "version": db_val.split()[-1] if len(db_val.split()) > 1 else "",
            "component_status": s,
            "eol_date": eol,
            "reason": r,
            "confidence": 8
        })

    return components

# ─── STEP 3: Technology Assessment ────────────────────────────────────────────
def step3_tech_assessment(apps):
    out_dir = os.path.join(OUTPUT_DIR, "technology_assessment")
    os.makedirs(out_dir, exist_ok=True)
    results = {}
    for aid in IN_SCOPE_IDS:
        app = apps[aid]
        components = get_tech_components(app)
        has_eol = any(c["component_status"] == "EOL" for c in components)
        has_outdated = any(c["component_status"] == "OUTDATED" for c in components)
        has_missing = any(c["component_status"] == "NO_KNOWLEDGE" for c in components)
        result = {
            "_comment": COMMENT,
            "application_identifier": aid,
            "components_analyzed": components,
            "has_eol_components": has_eol,
            "has_outdated_components": has_outdated,
            "has_missing_version_data": has_missing,
            "analysis_timestamp": TIMESTAMP
        }
        results[aid] = result
        with open(os.path.join(out_dir, f"technology_assessment_{aid}.json"), "w") as f:
            json.dump(result, f, indent=2)
    print(f"  Step 3: {len(IN_SCOPE_IDS)} tech assessment files written.")
    return results

# ─── STEP 4: Complexity Assessment ────────────────────────────────────────────
def compute_complexity(app, tech_result):
    aid = app["app_id"]
    servers = len(app.get("server_instances", [])) if isinstance(app.get("server_instances"), list) else 1
    interfaces = app.get("external_interface_count", 0)
    env_count = app.get("environment_count", 1)
    criticality = app.get("business_criticality", "Medium")
    containerized = app.get("is_containerized", "No")
    deployment = app.get("deployment_type", "")
    ci_cd = app.get("ci_cd_present", "No")
    arch = app.get("application_architecture", "")

    components = tech_result["components_analyzed"]
    eol_count = sum(1 for c in components if c["component_status"] == "EOL")
    outdated_count = sum(1 for c in components if c["component_status"] == "OUTDATED")

    # Technology age score (25%)
    if eol_count >= 3:
        tech_score = 9
    elif eol_count == 2:
        tech_score = 8
    elif eol_count == 1:
        tech_score = 7
    elif outdated_count >= 3:
        tech_score = 6
    elif outdated_count >= 2:
        tech_score = 5
    elif outdated_count == 1:
        tech_score = 4
    else:
        tech_score = 2

    # Integration complexity (20%)
    if interfaces >= 20:
        integ_score = 9
    elif interfaces >= 15:
        integ_score = 8
    elif interfaces >= 10:
        integ_score = 7
    elif interfaces >= 7:
        integ_score = 6
    elif interfaces >= 5:
        integ_score = 5
    elif interfaces >= 3:
        integ_score = 4
    elif interfaces >= 1:
        integ_score = 3
    else:
        integ_score = 1

    # Infrastructure (15%)
    infra_raw = servers + env_count
    if infra_raw >= 6:
        infra_score = 8
    elif infra_raw >= 4:
        infra_score = 6
    elif infra_raw >= 3:
        infra_score = 4
    else:
        infra_score = 2

    # Business criticality (15%)
    crit_map = {"Critical": 9, "High": 7, "Medium": 5, "Low": 3}
    crit_score = crit_map.get(criticality, 5)

    # Architecture/code complexity (15%)
    arch_score = 5
    lang = app.get("programming_language", "")
    if lang in ("COBOL-2014", "FORTRAN 2018", "Perl"):
        arch_score = 8
    elif arch == "1-Tier":
        arch_score = 7
    elif containerized == "No" and arch == "3-Tier":
        arch_score = 5
    elif containerized == "Yes":
        arch_score = 3

    # Data complexity (10%)
    db = app.get("database_engine", "")
    if "Oracle" in db or "DB2" in db:
        data_score = 8
    elif "SQL Server" in db:
        data_score = 5
    elif any(x in db for x in ["PostgreSQL", "MySQL", "MongoDB", "Aurora"]):
        data_score = 4
    else:
        data_score = 5

    final = (tech_score * 0.25 + integ_score * 0.20 + infra_score * 0.15 +
             crit_score * 0.15 + arch_score * 0.15 + data_score * 0.10)
    score = min(10, max(1, round(final)))

    if score <= 3:
        classification = "LOW"
    elif score <= 6:
        classification = "MEDIUM"
    else:
        classification = "HIGH"

    reasoning = (f"Technology age score {tech_score} ({eol_count} EOL, {outdated_count} outdated components). "
                 f"Integration score {integ_score} ({interfaces} external interfaces). "
                 f"Infrastructure score {infra_score} ({servers} servers, {env_count} environments). "
                 f"Criticality score {crit_score} ({criticality}). "
                 f"Architecture score {arch_score}. Data score {data_score}. "
                 f"Weighted final: {final:.1f} → {score} ({classification}).")

    return {
        "_comment": COMMENT,
        "application_identifier": aid,
        "complexity_score": score,
        "complexity_class": classification,
        "confidence": 8,
        "reasoning": reasoning,
        "contributing_factors": {
            "number_of_servers": servers,
            "number_of_databases": 1,
            "number_of_environments": env_count,
            "number_of_interfaces": interfaces,
            "business_criticality": criticality,
            "number_of_outdated_technologies": outdated_count,
            "number_of_eol_technologies": eol_count,
            "number_of_dependencies": 0,
            "ci_cd_present": ci_cd,
            "containerized": containerized
        }
    }

def step4_complexity(apps, tech_results):
    out_dir = os.path.join(OUTPUT_DIR, "complexity_results")
    os.makedirs(out_dir, exist_ok=True)
    results = {}
    for aid in IN_SCOPE_IDS:
        result = compute_complexity(apps[aid], tech_results[aid])
        results[aid] = result
        with open(os.path.join(out_dir, f"complexity_{aid}.json"), "w") as f:
            json.dump(result, f, indent=2)
    print(f"  Step 4: {len(IN_SCOPE_IDS)} complexity files written.")
    return results

# ─── STEP 5: Scenario Analysis ────────────────────────────────────────────────
SCENARIOS = [
    "os_update_security_patch",
    "switch_to_standard_linux_os",
    "switch_to_arm_cpu",
    "application_server_replacement",
    "app_deployment_to_cloud",
    "app_containerization",
    "app_refactor_decoupling",
    "upgrade_legacy_databases",
    "switch_db_engine_open_source",
    "update_outdated_components",
]

def assess_scenarios(app, tech_result):
    aid = app["app_id"]
    os_val = app.get("operating_system", "")
    lang = app.get("programming_language", "")
    server = app.get("application_server")
    db = app.get("database_engine", "")
    containerized = app.get("is_containerized", "No")
    deployment = app.get("deployment_type", "")
    solution = app.get("solution_type", "")
    arch = app.get("application_architecture", "")
    criticality = app.get("business_criticality", "")

    components = tech_result["components_analyzed"]
    os_comp = next((c for c in components if c["component_type"] == "os"), None)
    server_comp = next((c for c in components if c["component_type"] == "application_server"), None)
    db_comp = next((c for c in components if c["component_type"] == "database"), None)
    lang_comp = next((c for c in components if c["component_type"] == "programming_language"), None)

    os_status = os_comp["component_status"] if os_comp else "NO_KNOWLEDGE"
    server_status = server_comp["component_status"] if server_comp else None
    db_status = db_comp["component_status"] if db_comp else "NO_KNOWLEDGE"
    lang_status = lang_comp["component_status"] if lang_comp else "NO_KNOWLEDGE"

    is_custom = "custom" in solution.lower()
    is_oss = "open source" in solution.lower() or "open_source" in solution.lower()
    is_3p = "3rd party" in solution.lower()
    is_cloud = "aws" in deployment.lower()
    is_on_prem = "on-premise" in deployment.lower() or "on_premise" in deployment.lower()
    is_hybrid = "+" in deployment.lower()
    is_linux = any(x in os_val for x in ["RHEL", "CentOS", "Debian", "Ubuntu", "AIX"])
    is_aix = "AIX" in os_val
    is_windows = "Windows" in os_val

    def sc(scenario_id, status, reason, confidence=8):
        return {
            "id": scenario_id,
            "status": status,
            "match_type": "ai",
            "reason": reason,
            "confidence": confidence,
            "source": {"document_id": "", "document_title": "", "section": "", "content_excerpt": "", "relevance": ""}
        }

    scenarios = []

    # os_update_security_patch
    if os_status in ("EOL", "OUTDATED"):
        scenarios.append(sc("os_update_security_patch", "APPLICABLE",
            f"OS '{os_val}' is {os_status} and requires security patching or upgrade."))
    else:
        scenarios.append(sc("os_update_security_patch", "FULFILLED",
            f"OS '{os_val}' is current and receiving security patches."))

    # switch_to_standard_linux_os
    if is_windows:
        scenarios.append(sc("switch_to_standard_linux_os", "NOT_APPLICABLE",
            f"OS '{os_val}' is Windows; switching to Linux is not applicable."))
    elif is_aix:
        scenarios.append(sc("switch_to_standard_linux_os", "APPLICABLE",
            f"OS '{os_val}' is proprietary AIX; migrating to standard Linux would improve standardization."))
    elif is_linux and not is_aix:
        scenarios.append(sc("switch_to_standard_linux_os", "FULFILLED",
            f"OS '{os_val}' is already a standard Linux distribution."))
    else:
        scenarios.append(sc("switch_to_standard_linux_os", "LACK_OF_DATA",
            f"OS '{os_val}' classification unclear.", 5))

    # switch_to_arm_cpu
    scenarios.append(sc("switch_to_arm_cpu", "LACK_OF_DATA",
        "No explicit CPU architecture data (x86 vs ARM) is available in the application model.", 4))

    # application_server_replacement
    if server is None:
        scenarios.append(sc("application_server_replacement", "NOT_APPLICABLE",
            "No application server is used by this application."))
    elif is_3p:
        scenarios.append(sc("application_server_replacement", "BLOCKED",
            f"Application is 3rd party software; app server replacement depends on vendor."))
    elif server_status == "EOL":
        scenarios.append(sc("application_server_replacement", "APPLICABLE",
            f"Application server '{server}' is EOL and must be replaced."))
    elif server_status == "OUTDATED":
        scenarios.append(sc("application_server_replacement", "APPLICABLE",
            f"Application server '{server}' is outdated and should be upgraded."))
    elif server_status == "CURRENT_VERSION":
        scenarios.append(sc("application_server_replacement", "FULFILLED",
            f"Application server '{server}' is current."))
    else:
        scenarios.append(sc("application_server_replacement", "LACK_OF_DATA",
            f"Cannot assess application server '{server}' status.", 5))

    # app_deployment_to_cloud
    if is_cloud and not is_on_prem:
        scenarios.append(sc("app_deployment_to_cloud", "FULFILLED",
            f"Application is already deployed to cloud ({deployment})."))
    elif is_hybrid:
        scenarios.append(sc("app_deployment_to_cloud", "PARTIALLY_FULFILLED",
            f"Application has hybrid deployment ({deployment}); full cloud migration possible.", 7))
    else:
        scenarios.append(sc("app_deployment_to_cloud", "APPLICABLE",
            f"Application is on-premise ({deployment}); cloud migration (lift & shift) is applicable."))

    # app_containerization
    if containerized.lower() == "yes":
        scenarios.append(sc("app_containerization", "FULFILLED",
            "Application is already containerized."))
    elif is_3p:
        scenarios.append(sc("app_containerization", "BLOCKED",
            "3rd party application; containerization depends on vendor support."))
    elif is_windows and not any(x in lang for x in ["ASP.NET Core", "C# .NET", ".NET Core"]):
        scenarios.append(sc("app_containerization", "APPLICABLE",
            f"Application runs on Windows ({os_val}) and is not containerized; containerization possible with Windows containers."))
    elif is_custom or is_oss:
        scenarios.append(sc("app_containerization", "APPLICABLE",
            f"Custom/open-source application not yet containerized; containerization is applicable."))
    else:
        scenarios.append(sc("app_containerization", "APPLICABLE",
            "Application is not containerized; containerization should be evaluated."))

    # app_refactor_decoupling
    if is_3p:
        scenarios.append(sc("app_refactor_decoupling", "NOT_APPLICABLE",
            "3rd party application; refactoring is not applicable."))
    elif arch in ("1-Tier",) and is_custom:
        scenarios.append(sc("app_refactor_decoupling", "APPLICABLE",
            f"Application has {arch} architecture and is custom-built; refactoring and de-coupling is strongly recommended."))
    elif lang in ("COBOL-2014", "FORTRAN 2018"):
        scenarios.append(sc("app_refactor_decoupling", "APPLICABLE",
            f"Legacy language ({lang}) indicates monolithic architecture needing modernization."))
    elif is_custom and arch not in ("Microservices",):
        scenarios.append(sc("app_refactor_decoupling", "APPLICABLE",
            f"Custom application with {arch} architecture; refactoring to reduce coupling is applicable."))
    else:
        scenarios.append(sc("app_refactor_decoupling", "APPLICABLE",
            "Application may benefit from refactoring and de-coupling."))

    # upgrade_legacy_databases
    if db_status in ("EOL", "OUTDATED"):
        scenarios.append(sc("upgrade_legacy_databases", "APPLICABLE",
            f"Database '{db}' is {db_status}; upgrade is required."))
    elif db_status == "CURRENT_VERSION":
        scenarios.append(sc("upgrade_legacy_databases", "FULFILLED",
            f"Database '{db}' is current."))
    else:
        scenarios.append(sc("upgrade_legacy_databases", "LACK_OF_DATA",
            f"Cannot assess database '{db}' status.", 5))

    # switch_db_engine_open_source
    is_proprietary_db = any(x in db for x in ["Oracle", "DB2", "SQL Server"])
    is_oss_db = any(x in db for x in ["PostgreSQL", "MySQL", "MongoDB", "Aurora"])
    if is_3p:
        scenarios.append(sc("switch_db_engine_open_source", "NOT_APPLICABLE",
            "3rd party application; database engine change depends on vendor."))
    elif is_oss_db or "RDS" in db or "Aurora" in db:
        scenarios.append(sc("switch_db_engine_open_source", "FULFILLED",
            f"Database '{db}' is already open-source or managed open-source."))
    elif is_proprietary_db and (is_custom or is_oss):
        scenarios.append(sc("switch_db_engine_open_source", "APPLICABLE",
            f"Proprietary database '{db}' with custom app; switching to open-source DB is applicable."))
    else:
        scenarios.append(sc("switch_db_engine_open_source", "LACK_OF_DATA",
            f"Cannot determine applicability for database '{db}'.", 5))

    # update_outdated_components
    any_non_current = any(
        c["component_status"] in ("EOL", "OUTDATED") for c in components
    )
    if any_non_current:
        non_current = [c["component_name"] for c in components if c["component_status"] in ("EOL", "OUTDATED")]
        scenarios.append(sc("update_outdated_components", "APPLICABLE",
            f"Outdated/EOL components found: {', '.join(non_current)}. Updates required."))
    else:
        scenarios.append(sc("update_outdated_components", "FULFILLED",
            "All components are current."))

    return scenarios

def step5_scenario_analysis(apps, tech_results):
    out_dir = os.path.join(OUTPUT_DIR, "scenario_applicability_results")
    os.makedirs(out_dir, exist_ok=True)
    results = {}
    for aid in IN_SCOPE_IDS:
        scenarios = assess_scenarios(apps[aid], tech_results[aid])
        result = {
            "_comment": COMMENT,
            "application_identifier": aid,
            "scenarios_detailed": scenarios
        }
        results[aid] = result
        with open(os.path.join(out_dir, f"scenario_assessment_{aid}.json"), "w") as f:
            json.dump(result, f, indent=2)
    print(f"  Step 5: {len(IN_SCOPE_IDS)} scenario files written.")
    return results

# ─── STEP 6: Business Case ────────────────────────────────────────────────────
FINANCE = {
    "os_update_security_patch": {"base_cost": 1000, "base_savings": 500},
    "switch_to_standard_linux_os": {"base_cost": 300, "base_savings": 400},
    "switch_to_arm_cpu": {"base_cost": 5000, "base_savings": 1000},
    "application_server_replacement": {"base_cost": 10000, "base_savings": 12000},
    "app_deployment_to_cloud": {"base_cost": 5000, "base_savings": 3000},
    "app_containerization": {"base_cost": 100000, "base_savings": 100000},
    "app_refactor_decoupling": {"base_cost": 250000, "base_savings": 150000},
    "upgrade_legacy_databases": {"base_cost": 10000, "base_savings": 10000},
    "switch_db_engine_open_source": {"base_cost": 25000, "base_savings": 15000},  # mapped from switch_db_engine_postgresql
    # update_outdated_components has no finance config
}

APP_FOCUS_SCENARIOS = {
    "app_containerization", "app_refactor_decoupling", "application_server_replacement",
    "app_deployment_to_cloud"
}

def step6_business_case(apps, complexity_results, scenario_results):
    all_app_cases = []
    portfolio_totals = {}

    for aid in IN_SCOPE_IDS:
        score = complexity_results[aid]["complexity_score"]
        cost_mult = 0.5 * (1.15 ** score)
        # Savings multiplier for app-focus
        if score <= 3:
            savings_mult_app = 1.0
        elif score <= 6:
            savings_mult_app = 0.9
        else:
            savings_mult_app = 0.8

        app_scenarios = scenario_results[aid]["scenarios_detailed"]
        applicable = [s for s in app_scenarios if s["status"] == "APPLICABLE"]

        app_case = {
            "application_identifier": aid,
            "application_name": apps[aid]["app_name"],
            "complexity_score": score,
            "scenarios": []
        }

        for s in applicable:
            sid = s["id"]
            if sid not in FINANCE:
                continue
            fin = FINANCE[sid]
            cost = round(fin["base_cost"] * cost_mult, 2)
            sm = savings_mult_app if sid in APP_FOCUS_SCENARIOS else 1.0
            savings = round(fin["base_savings"] * sm, 2)
            roi_3yr = round(((savings * 3) - cost) / cost * 100, 1) if cost > 0 else 0
            payback = round(cost / savings, 1) if savings > 0 else 99

            app_case["scenarios"].append({
                "scenario_id": sid,
                "implementation_cost": cost,
                "annual_savings": savings,
                "roi_3_year_pct": roi_3yr,
                "payback_years": payback
            })

            # Portfolio totals
            if sid not in portfolio_totals:
                portfolio_totals[sid] = {"total_cost": 0, "total_savings": 0, "app_count": 0}
            portfolio_totals[sid]["total_cost"] += cost
            portfolio_totals[sid]["total_savings"] += savings
            portfolio_totals[sid]["app_count"] += 1

        all_app_cases.append(app_case)

    result = {
        "_comment": COMMENT,
        "portfolio_summary": {
            "total_in_scope_apps": len(IN_SCOPE_IDS),
            "scenarios_analyzed": list(FINANCE.keys()),
            "by_scenario": [
                {
                    "scenario_id": sid,
                    "applicable_app_count": v["app_count"],
                    "total_implementation_cost": round(v["total_cost"], 2),
                    "total_annual_savings": round(v["total_savings"], 2),
                    "portfolio_roi_3yr_pct": round(((v["total_savings"] * 3 - v["total_cost"]) / v["total_cost"] * 100), 1) if v["total_cost"] > 0 else 0
                }
                for sid, v in portfolio_totals.items()
            ],
            "grand_total_cost": round(sum(v["total_cost"] for v in portfolio_totals.values()), 2),
            "grand_total_annual_savings": round(sum(v["total_savings"] for v in portfolio_totals.values()), 2)
        },
        "applications": all_app_cases
    }

    out_dir = os.path.join(OUTPUT_DIR, "business_case_results")
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "business_case.json"), "w") as f:
        json.dump(result, f, indent=2)
    print("  Step 6: business_case.json written.")
    return result

# ─── STEP 7: Markdown Reports ─────────────────────────────────────────────────
EMOJI = {"CURRENT_VERSION": "🟢", "OUTDATED": "🟡", "EOL": "🔴", "NO_KNOWLEDGE": "⚪"}
STATUS_LABEL = {"CURRENT_VERSION": "CURRENT", "OUTDATED": "OUTDATED", "EOL": "EOL", "NO_KNOWLEDGE": "N/A"}

def render_app_md(app, tech, complexity, scenario, biz_case):
    aid = app["app_id"]
    name = app["app_name"]
    score = complexity["complexity_score"]
    cls = complexity["complexity_class"]
    
    # Find business case for this app
    app_biz = next((a for a in biz_case["applications"] if a["application_identifier"] == aid), None)

    lines = [
        f"<!-- generated by AI in Github cloud -->",
        f"# {name} ({aid})",
        "",
        "## Application Overview",
        "",
        "| Attribute | Value |",
        "|-----------|-------|",
        f"| **App ID** | {aid} |",
        f"| **Name** | {name} |",
        f"| **Status** | {app.get('application_status','N/A')} |",
        f"| **Criticality** | {app.get('business_criticality','N/A')} |",
        f"| **Solution Type** | {app.get('solution_type','N/A')} |",
        f"| **Deployment** | {app.get('deployment_type','N/A')} |",
        f"| **Containerized** | {app.get('is_containerized','N/A')} |",
        f"| **Architecture** | {app.get('application_architecture','N/A')} |",
        f"| **Business Unit** | {app.get('business_unit','N/A')} |",
        f"| **External Interfaces** | {app.get('external_interface_count',0)} |",
        f"| **Servers** | {len(app.get('server_instances',[])) if isinstance(app.get('server_instances'), list) else 1} |",
        f"| **Environments** | {app.get('environment_count',1)} |",
        "",
        "## Technology Stack",
        "",
        "| Component | Type | Version | Status | EOL Date |",
        "|-----------|------|---------|--------|----------|",
    ]
    for c in tech["components_analyzed"]:
        em = EMOJI.get(c["component_status"], "⚪")
        lbl = STATUS_LABEL.get(c["component_status"], c["component_status"])
        eol = c["eol_date"] or "N/A"
        lines.append(f"| {c['component_name']} | {c['component_type']} | {c['version']} | {em} {lbl} | {eol} |")
    
    lines += [""]

    # Pie chart
    eol_n = sum(1 for c in tech["components_analyzed"] if c["component_status"] == "EOL")
    out_n = sum(1 for c in tech["components_analyzed"] if c["component_status"] == "OUTDATED")
    cur_n = sum(1 for c in tech["components_analyzed"] if c["component_status"] == "CURRENT_VERSION")
    total_n = len(tech["components_analyzed"])

    lines += [
        "```mermaid",
        "pie title Technology Health",
    ]
    if cur_n: lines.append(f'    "Current" : {cur_n}')
    if out_n: lines.append(f'    "Outdated" : {out_n}')
    if eol_n: lines.append(f'    "EOL" : {eol_n}')
    lines += ["```", ""]

    # Complexity
    lines += [
        "## Complexity Assessment",
        "",
        f"**Score: {score}/10 ({cls})**",
        "",
        complexity["reasoning"],
        "",
        "| Factor | Value |",
        "|--------|-------|",
    ]
    for k, v in complexity["contributing_factors"].items():
        lines.append(f"| {k.replace('_',' ').title()} | {v} |")
    lines += [""]

    # Scenarios
    applicable_sc = [s for s in scenario["scenarios_detailed"] if s["status"] in ("APPLICABLE", "PARTIALLY_FULFILLED")]
    other_sc = [s for s in scenario["scenarios_detailed"] if s["status"] not in ("APPLICABLE", "PARTIALLY_FULFILLED")]

    lines += ["## Applicable Modernization Scenarios", ""]
    if applicable_sc:
        for s in applicable_sc:
            lines += [f"### {s['id'].replace('_',' ').title()}", f"- **Status**: {s['status']}", f"- **Reason**: {s['reason']}", f"- **Confidence**: {s['confidence']}/10", ""]
    else:
        lines += ["_No applicable scenarios._", ""]

    lines += ["## Other Scenarios", "", "| Scenario | Status | Reason |", "|----------|--------|--------|"]
    for s in other_sc:
        lines.append(f"| {s['id']} | {s['status']} | {s['reason'][:80]}... |" if len(s['reason']) > 80 else f"| {s['id']} | {s['status']} | {s['reason']} |")
    lines += [""]

    # Financial
    lines += ["## Financial Summary", ""]
    if app_biz and app_biz["scenarios"]:
        lines += ["| Scenario | Cost (USD) | Annual Savings (USD) | ROI 3yr % | Payback (yrs) |",
                  "|----------|-----------|---------------------|-----------|---------------|"]
        total_cost = sum(x["implementation_cost"] for x in app_biz["scenarios"])
        total_sav = sum(x["annual_savings"] for x in app_biz["scenarios"])
        for x in app_biz["scenarios"]:
            lines.append(f"| {x['scenario_id']} | ${x['implementation_cost']:,.0f} | ${x['annual_savings']:,.0f} | {x['roi_3_year_pct']}% | {x['payback_years']} |")
        lines += [f"| **TOTAL** | **${total_cost:,.0f}** | **${total_sav:,.0f}** | | |", ""]
    else:
        lines += ["_No financial data available for applicable scenarios._", ""]

    return "\n".join(lines)


def step7_app_reports(apps, tech_results, complexity_results, scenario_results, biz_case):
    out_dir = os.path.join(OUTPUT_DIR, "reports/apps")
    os.makedirs(out_dir, exist_ok=True)
    for aid in IN_SCOPE_IDS:
        md = render_app_md(apps[aid], tech_results[aid], complexity_results[aid],
                           scenario_results[aid], biz_case)
        with open(os.path.join(out_dir, f"{aid}.md"), "w") as f:
            f.write(md)
    print(f"  Step 7a: {len(IN_SCOPE_IDS)} app markdown reports written.")


def step7_portfolio_report(apps, tech_results, complexity_results, scenario_results, biz_case):
    # Aggregates
    score_dist = {"LOW": 0, "MEDIUM": 0, "HIGH": 0}
    for aid in IN_SCOPE_IDS:
        score_dist[complexity_results[aid]["complexity_class"]] += 1

    tech_health = {"CURRENT_VERSION": 0, "OUTDATED": 0, "EOL": 0}
    for aid in IN_SCOPE_IDS:
        for c in tech_results[aid]["components_analyzed"]:
            s = c["component_status"]
            if s in tech_health:
                tech_health[s] += 1

    # Scenario counts
    scenario_counts = {}
    for aid in IN_SCOPE_IDS:
        for s in scenario_results[aid]["scenarios_detailed"]:
            if s["id"] not in scenario_counts:
                scenario_counts[s["id"]] = {"APPLICABLE": 0, "FULFILLED": 0, "NOT_APPLICABLE": 0, "BLOCKED": 0, "LACK_OF_DATA": 0, "PARTIALLY_FULFILLED": 0}
            scenario_counts[s["id"]][s["status"]] = scenario_counts[s["id"]].get(s["status"], 0) + 1

    ps = biz_case["portfolio_summary"]

    lines = [
        "<!-- generated by AI in Github cloud -->",
        "# Portfolio Modernization Report",
        "",
        "## Executive Summary",
        "",
        (f"The portfolio consists of **{len(IN_SCOPE_IDS)} in-scope applications** (4 retired/out-of-scope). "
         f"Technology health analysis reveals significant modernization needs: {tech_health['EOL']} EOL component instances "
         f"and {tech_health['OUTDATED']} outdated component instances across the portfolio. "
         f"Complexity distribution shows {score_dist['HIGH']} HIGH, {score_dist['MEDIUM']} MEDIUM, and {score_dist['LOW']} LOW complexity applications. "
         f"Estimated total modernization investment: **${ps['grand_total_cost']:,.0f}** with **${ps['grand_total_annual_savings']:,.0f}** annual savings potential."),
        "",
        "## Complexity Distribution",
        "",
        "```mermaid",
        "pie title Application Complexity",
        f'    "LOW (1-3)" : {score_dist["LOW"]}',
        f'    "MEDIUM (4-6)" : {score_dist["MEDIUM"]}',
        f'    "HIGH (7-10)" : {score_dist["HIGH"]}',
        "```",
        "",
        "## Technology Health Overview",
        "",
        "```mermaid",
        "pie title Technology Component Health",
        f'    "Current" : {tech_health["CURRENT_VERSION"]}',
        f'    "Outdated" : {tech_health["OUTDATED"]}',
        f'    "EOL" : {tech_health["EOL"]}',
        "```",
        "",
        "## Scenario Applicability Matrix",
        "",
        "| Scenario | Applicable | Fulfilled | Not Applicable | Blocked | Lack of Data |",
        "|----------|-----------|-----------|---------------|---------|--------------|",
    ]
    for sid, counts in scenario_counts.items():
        lines.append(f"| {sid} | {counts.get('APPLICABLE',0)+counts.get('PARTIALLY_FULFILLED',0)} | {counts.get('FULFILLED',0)} | {counts.get('NOT_APPLICABLE',0)} | {counts.get('BLOCKED',0)} | {counts.get('LACK_OF_DATA',0)} |")

    lines += [
        "",
        "## Top Modernization Opportunities",
        "",
        "```mermaid",
        "bar",
        "    title Applicable Scenarios Count",
    ]
    for sid, counts in scenario_counts.items():
        cnt = counts.get("APPLICABLE", 0) + counts.get("PARTIALLY_FULFILLED", 0)
        if cnt > 0:
            lines.append(f'    "{sid[:30]}" : {cnt}')
    lines += ["```", ""]

    lines += [
        "## Financial Summary",
        "",
        "| Scenario | Applicable Apps | Total Cost (USD) | Annual Savings (USD) | Portfolio ROI 3yr % |",
        "|----------|----------------|-----------------|---------------------|---------------------|",
    ]
    for item in ps["by_scenario"]:
        lines.append(f"| {item['scenario_id']} | {item['applicable_app_count']} | ${item['total_implementation_cost']:,.0f} | ${item['total_annual_savings']:,.0f} | {item['portfolio_roi_3yr_pct']}% |")
    lines += [
        f"| **TOTAL** | | **${ps['grand_total_cost']:,.0f}** | **${ps['grand_total_annual_savings']:,.0f}** | |",
        "",
        "## Risk Applications",
        "",
        "| App ID | Name | Criticality | Complexity | EOL Components | Outdated Components |",
        "|--------|------|------------|------------|---------------|---------------------|",
    ]
    for aid in IN_SCOPE_IDS:
        app = apps[aid]
        tech = tech_results[aid]
        comp = complexity_results[aid]
        eol_n = sum(1 for c in tech["components_analyzed"] if c["component_status"] == "EOL")
        out_n = sum(1 for c in tech["components_analyzed"] if c["component_status"] == "OUTDATED")
        if eol_n > 0 or comp["complexity_score"] >= 7:
            lines.append(f"| {aid} | {app['app_name']} | {app['business_criticality']} | {comp['complexity_score']} ({comp['complexity_class']}) | {eol_n} | {out_n} |")

    lines += [
        "",
        "## Application Reports",
        "",
        "| App ID | Name | Complexity | Tech Health |",
        "|--------|------|------------|-------------|",
    ]
    for aid in IN_SCOPE_IDS:
        app = apps[aid]
        comp = complexity_results[aid]
        tech = tech_results[aid]
        eol_n = sum(1 for c in tech["components_analyzed"] if c["component_status"] == "EOL")
        out_n = sum(1 for c in tech["components_analyzed"] if c["component_status"] == "OUTDATED")
        lines.append(f"| [{aid}](apps/{aid}.md) | {app['app_name']} | {comp['complexity_score']} ({comp['complexity_class']}) | 🔴 {eol_n} EOL / 🟡 {out_n} Outdated |")

    with open(os.path.join(OUTPUT_DIR, "reports/portfolio_report.md"), "w") as f:
        f.write("\n".join(lines))
    print("  Step 7b: portfolio_report.md written.")


# ─── Consolidated schema ──────────────────────────────────────────────────────
def write_consolidated_schema(apps):
    out_dir = os.path.join(OUTPUT_DIR, "applications/consolidated_schema")
    os.makedirs(out_dir, exist_ok=True)
    for aid, app in apps.items():
        result = {"_comment": COMMENT}
        result.update(app)
        with open(os.path.join(out_dir, f"consolidated_schema_application_{aid}.json"), "w") as f:
            json.dump(result, f, indent=2)
    print(f"  Consolidated schema: {len(apps)} files written.")


# ─── Main ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("Loading apps...")
    apps = load_apps()

    print("Step 2: Out-of-scope assessment...")
    step2_out_of_scope(apps)

    print("Step 3: Technology assessment...")
    tech_results = step3_tech_assessment(apps)

    print("Step 4: Complexity assessment...")
    complexity_results = step4_complexity(apps, tech_results)

    print("Step 5: Scenario analysis...")
    scenario_results = step5_scenario_analysis(apps, tech_results)

    print("Step 6: Business case...")
    biz_case = step6_business_case(apps, complexity_results, scenario_results)

    print("Step 7: Reports...")
    step7_app_reports(apps, tech_results, complexity_results, scenario_results, biz_case)
    step7_portfolio_report(apps, tech_results, complexity_results, scenario_results, biz_case)

    print("Consolidated schema...")
    write_consolidated_schema(apps)

    print("All steps complete!")
