# generated by AI in Github cloud

# generated by AI in Github cloud
class GreetingRepository:
    def get_greeting_template(self) -> str:
        return "Hello %s"

    def get_default_recipient(self) -> str:
        return "World"
