# generated by AI in Github cloud

from greeting_service import GreetingService


# generated by AI in Github cloud
class GreetingController:
    def __init__(self, greeting_service: GreetingService) -> None:
        if greeting_service is None:
            raise ValueError("greeting_service must not be null")
        self._greeting_service = greeting_service

    def greet(self, args: list[str] | None) -> str:
        if args is None or len(args) == 0:
            return self._greeting_service.create_greeting(None)
        return self._greeting_service.create_greeting(args[0])
