# generated by AI in Github cloud

from greeting_repository import GreetingRepository


# generated by AI in Github cloud
class GreetingService:
    def __init__(self, greeting_repository: GreetingRepository) -> None:
        if greeting_repository is None:
            raise ValueError("greeting_repository must not be null")
        self._greeting_repository = greeting_repository

    def create_greeting(self, requested_recipient: str | None) -> str:
        recipient = (
            self._greeting_repository.get_default_recipient()
            if requested_recipient is None or requested_recipient.strip() == ""
            else requested_recipient.strip()
        )
        return self._greeting_repository.get_greeting_template() % recipient
