# generated by AI in Github cloud

import sys

from greeting_controller import GreetingController
from greeting_repository import GreetingRepository
from greeting_service import GreetingService


def main(args: list[str] | None = None) -> None:
    repository = GreetingRepository()
    service = GreetingService(repository)
    controller = GreetingController(service)
    resolved_args = sys.argv[1:] if args is None else args
    print(controller.greet(resolved_args))


if __name__ == "__main__":
    main()
