// generated by AI in Github cloud
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

// generated by AI in Github cloud
public record CustomerDto(
        Long id,
        @NotBlank(message = "name is required") String name,
        @Email(message = "email must be valid") @NotBlank(message = "email is required") String email) {
}
