// generated by AI in Github cloud
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;
import java.util.logging.Logger;
import org.springframework.stereotype.Service;

// generated by AI in Github cloud
@Service
public class CustomerService {
    private static final Logger LOGGER = Logger.getLogger(CustomerService.class.getName());
    private final ConcurrentHashMap<Long, CustomerEntity> store = new ConcurrentHashMap<>();
    private final AtomicLong idGenerator = new AtomicLong(0);

    public List<CustomerDto> findAll() {
        return store.values().stream().map(this::toDto).toList();
    }

    public CustomerDto create(CustomerDto request) {
        validate(request);
        var id = idGenerator.incrementAndGet();
        var entity = new CustomerEntity();
        entity.setId(id);
        entity.setName(request.name().trim());
        entity.setEmail(request.email().trim());
        store.put(id, entity);
        LOGGER.info("Created customer with id=" + id);
        return toDto(entity);
    }

    private void validate(CustomerDto request) {
        var errors = new ArrayList<String>();
        if (request == null) {
            throw new IllegalArgumentException("request must not be null");
        }
        if (request.name() == null || request.name().isBlank()) {
            errors.add("name is required");
        }
        if (request.email() == null || request.email().isBlank()) {
            errors.add("email is required");
        } else if (!request.email().contains("@")) {
            errors.add("email must be valid");
        }
        if (!errors.isEmpty()) {
            throw new IllegalArgumentException(String.join(", ", errors));
        }
    }

    private CustomerDto toDto(CustomerEntity entity) {
        return new CustomerDto(entity.getId(), entity.getName(), entity.getEmail());
    }
}
