// generated by AI in Github cloud

// generated by AI in Github cloud
public class GreetingRepository {

    public String getGreetingTemplate() {
        return "Hello %s";
    }

    public String getDefaultRecipient() {
        return "World";
    }
}
