// generated by AI in Github cloud

import java.util.Objects;

// generated by AI in Github cloud
public class GreetingService {

    private final GreetingRepository greetingRepository;

    public GreetingService(GreetingRepository greetingRepository) {
        this.greetingRepository = Objects.requireNonNull(greetingRepository, "greetingRepository must not be null");
    }

    public String createGreeting(String requestedRecipient) {
        var recipient = requestedRecipient == null || requestedRecipient.isBlank()
                ? greetingRepository.getDefaultRecipient()
                : requestedRecipient.trim();

        return greetingRepository.getGreetingTemplate().formatted(recipient);
    }
}
