// generated by AI in Github cloud

import java.util.Objects;

// generated by AI in Github cloud
public class GreetingController {

    private final GreetingService greetingService;

    public GreetingController(GreetingService greetingService) {
        this.greetingService = Objects.requireNonNull(greetingService, "greetingService must not be null");
    }

    public String greet(String[] args) {
        if (args == null || args.length == 0) {
            return greetingService.createGreeting(null);
        }

        return greetingService.createGreeting(args[0]);
    }
}
