// generated by AI in Github cloud

// generated by AI in Github cloud
public class HelloWorld {

    public static void main(String[] args) {
        var repository = new GreetingRepository();
        var service = new GreetingService(repository);
        var controller = new GreetingController(service);

        System.out.println(controller.greet(args));
    }
}
