#!/usr/bin/env bash
# =============================================================================
# setup-obligatory-skills.sh
#
# Creates all obligatory skill directories and SKILL.md files derived from
# the cookbooks in cookbooks/. Run this script once to materialise the skills
# so the transformation.migration agent can load them automatically via the
# glob pattern `obligatory_*`.
#
# Usage:
#   bash .specify/scripts/bash/setup-obligatory-skills.sh
#
# Safe to re-run: existing files are NOT overwritten (exits gracefully).
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
SKILLS_DIR="$REPO_ROOT/.github/skills"

echo "📂 Repository root : $REPO_ROOT"
echo "📂 Skills directory: $SKILLS_DIR"
echo ""

# ---------------------------------------------------------------------------
# Helper: write a skill file, skipping if it already exists
# ---------------------------------------------------------------------------
write_skill() {
    local skill_dir="$1"
    local content="$2"

    mkdir -p "$skill_dir"

    local skill_file="$skill_dir/SKILL.md"
    if [ -f "$skill_file" ]; then
        echo "  ⏭  Skipped (already exists): $skill_file"
    else
        printf '%s\n' "$content" > "$skill_file"
        echo "  ✅ Created: $skill_file"
    fi
}

# =============================================================================
# SKILL 1 — obligatory_ai-generated-comment
# Source cookbook: cookbooks/ai-generated-comment-guideline.md
# =============================================================================
echo "🔧 Setting up: obligatory_ai-generated-comment"

SKILL1_CONTENT='---
name: obligatory_ai-generated-comment
description: >
  Enforces the rule that every newly created file and every newly created class must include the exact comment
  "generated by AI in Github cloud" near the top of the file and directly above each class definition.
  Always apply this skill whenever creating new source files or new class definitions in any programming language
  during migration, code generation, or any other code-writing task. Never skip this comment even if the user
  does not explicitly ask for it — it is a mandatory auditability annotation.
---

# Skill: AI-Generated Comment Annotation

**Enforcement level:** Obligatory — apply to every new file and every new class without exception.

## Rule

Whenever a new file is created OR a new class is defined, include the following comment exactly as written:

```
generated by AI in Github cloud
```

The text must be **exact** — no variations, no punctuation changes, no capitalisation differences.

## Placement Rules

### New Files
- Add the comment at the **very top of the file**, before any imports, package declarations, or code.
- Place it as the **first line** (or immediately after a shebang line `#!/...` if one is required).

### New Classes
- Add the comment **directly above** each class definition (on the line immediately preceding the `class`
  keyword or equivalent).

## Language-Specific Comment Syntax

Use the appropriate single-line or block comment syntax for the target language:

| Language              | Comment style | Example                                      |
|-----------------------|---------------|----------------------------------------------|
| Python                | `#`           | `# generated by AI in Github cloud`          |
| Java                  | `//`          | `// generated by AI in Github cloud`         |
| JavaScript/TypeScript | `//`          | `// generated by AI in Github cloud`         |
| Kotlin                | `//`          | `// generated by AI in Github cloud`         |
| C / C++ / C#          | `//`          | `// generated by AI in Github cloud`         |
| Go                    | `//`          | `// generated by AI in Github cloud`         |
| Ruby                  | `#`           | `# generated by AI in Github cloud`          |
| Swift                 | `//`          | `// generated by AI in Github cloud`         |
| PHP                   | `//`          | `// generated by AI in Github cloud`         |
| Rust                  | `//`          | `// generated by AI in Github cloud`         |
| Markdown / YAML / TOML| `#`           | `# generated by AI in Github cloud`          |
| HTML / XML            | `<!-- -->`    | `<!-- generated by AI in Github cloud -->`   |
| SQL                   | `--`          | `-- generated by AI in Github cloud`         |
| Shell / Bash          | `#`           | `# generated by AI in Github cloud`          |

If the target language is not listed, use the language'\''s standard single-line comment delimiter.

## Examples

### Python — new file with a class

```python
# generated by AI in Github cloud

from dataclasses import dataclass

# generated by AI in Github cloud
@dataclass
class UserProfile:
    user_id: int
    username: str
```

### Java — new file with a class

```java
// generated by AI in Github cloud

package com.example.service;

// generated by AI in Github cloud
public class OrderService {
    // ...
}
```

### TypeScript — new file with a class

```typescript
// generated by AI in Github cloud

import { Injectable } from '\''@angular/core'\'';

// generated by AI in Github cloud
@Injectable({ providedIn: '\''root'\'' })
export class AuthService {
    // ...
}
```

## What Counts as "New"

- Any file that is **created** during this session (not an existing file being modified).
- Any class that is **added** to a file in this session — whether in a newly created file or appended
  to an existing file.
- **Modifying** an existing class does NOT require adding the comment retroactively.

## Checklist Before Finalising Any Output

Before delivering any newly created file, verify:
- [ ] File-level comment `generated by AI in Github cloud` is present at the top.
- [ ] Each class definition is preceded by `generated by AI in Github cloud`.
- [ ] The comment text is character-for-character exact.
- [ ] The correct comment syntax for the target language is used.'

write_skill "$SKILLS_DIR/obligatory_ai-generated-comment" "$SKILL1_CONTENT"

# =============================================================================
# SKILL 2 — obligatory_mermaid-architecture-documentation
# Source cookbook: cookbooks/mermaid-architecture-documentation-guideline.md
# =============================================================================
echo ""
echo "🔧 Setting up: obligatory_mermaid-architecture-documentation"

SKILL2_CONTENT='---
name: obligatory_mermaid-architecture-documentation
description: >
  Enforces the rule that all application architecture documentation must include Mermaid diagrams.
  Apply this skill whenever creating or updating architecture documents, README files that describe
  system structure, arc42 documents, ADRs, or any documentation that describes how components,
  services, or modules interact. Always add the required Mermaid diagrams even if the user does not
  explicitly ask for them — they are mandatory for architecture documentation.
---

# Skill: Mermaid Architecture Documentation

**Enforcement level:** Obligatory — every architecture document must contain the required Mermaid diagrams.

## Rule

When creating or updating application architecture documentation, always include Mermaid diagrams.
Three diagram types are the minimum requirement; additional diagrams are encouraged.

## Required Diagrams (minimum set)

Every architecture document MUST contain all three of the following:

### 1. High-Level System Context Diagram
Shows the system as a whole and its relationships with external actors and systems.

**Recommended syntax:** `flowchart TD` or `graph TD`

```mermaid
flowchart TD
    User([User]) --> App[Your Application]
    App --> DB[(Database)]
    App --> ExtAPI[External API]
```

### 2. Component / Module Interaction Diagram
Shows the internal components or modules and how they interact with each other.

**Recommended syntax:** `flowchart LR`, `graph LR`, or `classDiagram`

```mermaid
flowchart LR
    UI[UI Layer] --> SVC[Service Layer]
    SVC --> REPO[Repository Layer]
    REPO --> DB[(Database)]
```

### 3. Runtime Flow Diagram
Shows the step-by-step flow of a key user journey or service interaction at runtime.

**Recommended syntax:** `sequenceDiagram`

```mermaid
sequenceDiagram
    actor User
    User->>Controller: HTTP Request
    Controller->>Service: processRequest()
    Service->>Repository: findById(id)
    Repository-->>Service: entity
    Service-->>Controller: ResponseDTO
    Controller-->>User: HTTP Response
```

## Diagram Standards

- **Node naming**: diagram nodes MUST match real package/module/service/class names from the codebase.
- **No fictional components**: do not invent components that do not exist in the code.
- **Keep updated**: whenever architecture-relevant code changes, update the corresponding Mermaid diagrams.

## Recommended Mermaid Diagram Types Reference

| Diagram type      | Mermaid keyword     | Best for                                      |
|-------------------|---------------------|-----------------------------------------------|
| Process flow      | `flowchart`         | Request flows, data flows, process steps      |
| Component graph   | `graph TD / LR`     | Component dependency overviews                |
| Sequence          | `sequenceDiagram`   | Service interactions over time                |
| Class/domain model| `classDiagram`      | Domain model structure, entity relationships  |
| State machine     | `stateDiagram-v2`   | Lifecycle states of an entity or process      |
| Entity-relationship| `erDiagram`        | Database schema relationships                 |

## Example: Complete Architecture Document Section

```markdown
## System Architecture

### System Context

```mermaid
flowchart TD
    User([Browser Client]) --> Gateway[API Gateway]
    Gateway --> OrderSvc[Order Service]
    Gateway --> UserSvc[User Service]
    OrderSvc --> OrderDB[(Orders DB)]
    UserSvc --> UserDB[(Users DB)]
    OrderSvc --> PaymentAPI[Payment API]
```

### Component Interactions

```mermaid
flowchart LR
    OrderController --> OrderService
    OrderService --> OrderRepository
    OrderService --> PaymentClient
    OrderRepository --> OrderDB[(PostgreSQL)]
```

### Key Runtime Flow: Place Order

```mermaid
sequenceDiagram
    actor Client
    Client->>OrderController: POST /orders
    OrderController->>OrderService: createOrder(dto)
    OrderService->>PaymentClient: charge(amount)
    PaymentClient-->>OrderService: paymentConfirmation
    OrderService->>OrderRepository: save(order)
    OrderRepository-->>OrderService: savedOrder
    OrderService-->>OrderController: OrderResponseDTO
    OrderController-->>Client: 201 Created
```
```

## Checklist Before Finalising Any Architecture Document

- [ ] High-level system context diagram is present (using `flowchart` or `graph`).
- [ ] Component/module interaction diagram is present.
- [ ] Runtime flow diagram is present (using `sequenceDiagram`).
- [ ] All diagram nodes correspond to real names in the codebase.
- [ ] Diagrams are enclosed in fenced code blocks with the `mermaid` language tag.
- [ ] Diagrams have been updated if any architecture-relevant code changed.'

write_skill "$SKILLS_DIR/obligatory_mermaid-architecture-documentation" "$SKILL2_CONTENT"

# =============================================================================
# SKILL 3 — obligatory_java-to-python-migration-practices
# Source cookbook: cookbooks/java-to-python-migration-good-code-practices.md
# =============================================================================
echo ""
echo "🔧 Setting up: obligatory_java-to-python-migration-practices"

SKILL3_CONTENT='---
name: obligatory_java-to-python-migration-practices
description: >
  Enforces good code practices when migrating Java code to Python. Apply this skill for every file,
  class, or module produced during a Java-to-Python migration. These rules must be followed without
  exception: preserve behaviour via tests first, use Pythonic idioms over Java patterns, apply type
  hints and dataclasses, follow Python naming conventions, and validate each batch before continuing.
  Use this skill whenever the migration source is Java and the migration target is Python.
---

# Skill: Java-to-Python Migration — Good Code Practices

**Enforcement level:** Obligatory — all rules below apply to every migrated file without exception.

## Core Migration Rules

### 1. Preserve Behaviour First — Tests Before Refactoring

- Migrate or write equivalent tests **before** refactoring any logic.
- A migrated file is not complete until its tests pass.
- Do not skip tests on the grounds that "the logic is simple".

### 2. Translate to Focused Python Modules

- Java classes become **small, focused Python modules** — one responsibility per file.
- Do NOT create one large Python file that mirrors a Java package hierarchy.
- Use Python packages (`__init__.py`) to group related modules.

**Example:**
```
Java:  com/example/service/UserService.java  (500 lines)
Python: user/service.py                      (≤150 lines)
        user/repository.py
        user/models.py
```

### 3. Replace Getters/Setters with Python Properties (Only When Needed)

- Java-style `getX()` / `setX()` methods should be replaced with **`@property`** only when
  validation or computed logic is required.
- For plain data holders, use `dataclasses` or plain attributes — no getters/setters needed.

**Java:**
```java
public String getName() { return name; }
public void setName(String name) { this.name = name; }
```

**Python (simple case — no logic needed):**
```python
@dataclass
class User:
    name: str  # direct attribute, no property required
```

**Python (with validation):**
```python
@property
def name(self) -> str:
    return self._name

@name.setter
def name(self, value: str) -> None:
    if not value.strip():
        raise ValueError("Name cannot be blank")
    self._name = value
```

### 4. Use Type Hints and Dataclasses

- Add type hints to **all** function signatures and class fields.
- Use `@dataclass` for model/DTO classes to replace Java POJOs.
- Use `Optional[T]` or `T | None` instead of nullable references.

**Java:**
```java
public class OrderDTO {
    private int orderId;
    private String status;
    public OrderDTO(int orderId, String status) { ... }
}
```

**Python:**
```python
from dataclasses import dataclass

@dataclass
class OrderDTO:
    order_id: int
    status: str
```

### 5. Convert Checked Exceptions to Specific Python Exception Types

- Java checked exceptions → Python custom exception classes with clear names.
- Never use bare `except Exception` — always catch specific exception types.
- Never silently swallow exceptions.

**Java:**
```java
try {
    orderService.process(order);
} catch (OrderNotFoundException e) {
    logger.error("Order not found", e);
}
```

**Python:**
```python
class OrderNotFoundError(Exception):
    """Raised when an order cannot be located."""

try:
    order_service.process(order)
except OrderNotFoundError as exc:
    logger.error("Order not found: %s", exc)
```

### 6. Prefer Python Standard Libraries and Idioms

- Do NOT copy Java patterns into Python; use idiomatic Python instead.
- Prefer list/dict comprehensions over explicit loops where readability is maintained.
- Use `pathlib` instead of `java.io.File`-style string paths.
- Use `logging` module instead of `System.out.println`.
- Use `contextlib` / `with` statements for resource management (replaces `try-finally`).

**Avoid (Java pattern copied to Python):**
```python
result = []
for item in items:
    if item.is_active():
        result.append(item.get_name())
```

**Prefer (Pythonic):**
```python
result = [item.name for item in items if item.is_active]
```

### 7. Naming Conventions

Follow Python naming conventions strictly. Mixed-convention code is a migration defect.

| Element              | Convention     | Example                       |
|----------------------|----------------|-------------------------------|
| Functions            | `snake_case`   | `get_user_by_id()`            |
| Variables            | `snake_case`   | `user_name`, `order_count`    |
| Classes              | `PascalCase`   | `OrderService`, `UserProfile` |
| Constants            | `UPPER_SNAKE`  | `MAX_RETRY_COUNT = 3`         |
| Private attributes   | `_snake_case`  | `self._connection_pool`       |
| Module files         | `snake_case`   | `order_service.py`            |
| Packages (dirs)      | `snake_case`   | `user_management/`            |

### 8. Validate Performance-Sensitive Paths

- Java and Python have very different runtime characteristics (JIT vs. interpreted).
- After migrating any performance-sensitive path, run benchmarks and document the results.
- Consider `numpy`, `pandas`, or async patterns where Java used concurrency or bulk operations.

### 9. Run Linting, Tests, and Static Checks Per Batch

Before moving to the next migration batch, ALL of the following must pass:

- [ ] `pytest` — all tests pass (or explicit exceptions documented).
- [ ] `mypy` — no type errors on migrated files.
- [ ] `ruff` or `flake8` — no linting violations.
- [ ] Manual review of naming conventions.

**Do NOT proceed to the next file or module if the current batch has failing checks.**

## Migration Checklist Per File

Before marking a Python file as "migrated", verify:

- [ ] Equivalent test coverage exists and passes.
- [ ] File is focused (single responsibility, ≤ 200 lines guideline).
- [ ] No Java-style getters/setters unless a property with logic is justified.
- [ ] Type hints on all public functions and class fields.
- [ ] Custom exception classes defined for each distinct error condition.
- [ ] No Java idiom anti-patterns (no explicit setter loops, no `System.out.println`, etc.).
- [ ] All names follow `snake_case` (functions/variables) and `PascalCase` (classes).
- [ ] Linting and static checks pass.
- [ ] Performance-sensitive paths benchmarked if applicable.'

write_skill "$SKILLS_DIR/obligatory_java-to-python-migration-practices" "$SKILL3_CONTENT"

echo ""
echo "============================================================"
echo "✅ All obligatory skills have been set up successfully."
echo ""
echo "Skills created:"
echo "  • $SKILLS_DIR/obligatory_ai-generated-comment/SKILL.md"
echo "  • $SKILLS_DIR/obligatory_mermaid-architecture-documentation/SKILL.md"
echo "  • $SKILLS_DIR/obligatory_java-to-python-migration-practices/SKILL.md"
echo "============================================================"
