// generated by AI in Github cloud
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.Test;

// generated by AI in Github cloud
class HelloWorldTest {

    @Test
    void mainPrintsHelloWorldWithTrailingNewline() {
        var output = new ByteArrayOutputStream();
        var originalOut = System.out;

        try {
            System.setOut(new PrintStream(output, true, StandardCharsets.UTF_8));
            HelloWorld.main(new String[0]);
        } finally {
            System.setOut(originalOut);
        }

        assertEquals("Hello World" + System.lineSeparator(), output.toString(StandardCharsets.UTF_8));
    }
}
