# generated by AI in Github cloud

import io
import os
import pathlib
import sys
import unittest
from contextlib import redirect_stdout

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "main" / "python"))

from greeting_controller import GreetingController
from greeting_repository import GreetingRepository
from greeting_service import GreetingService
from hello_world import main


# generated by AI in Github cloud
class HelloWorldTest(unittest.TestCase):
    def test_main_prints_hello_world_with_trailing_newline(self) -> None:
        output = io.StringIO()
        with redirect_stdout(output):
            main([])
        self.assertEqual(f"Hello World{os_linesep()}", output.getvalue())

    def test_controller_uses_first_argument_as_recipient(self) -> None:
        controller = GreetingController(GreetingService(GreetingRepository()))
        self.assertEqual("Hello Copilot", controller.greet(["Copilot"]))

    def test_service_falls_back_to_default_recipient_for_blank_input(self) -> None:
        service = GreetingService(GreetingRepository())
        self.assertEqual("Hello World", service.create_greeting("   "))


def os_linesep() -> str:
    return os.linesep
