# generated by AI in Github cloud
"""Hello World application migrated from Java 21 to Python."""

from __future__ import annotations

import sys
from dataclasses import dataclass
from datetime import date, datetime
from enum import Enum


# ---------------------------------------------------------------------------
# Greeting
# ---------------------------------------------------------------------------

# generated by AI in Github cloud
@dataclass(frozen=True)
class Greeting:
    """Immutable value object holding a greeting message."""

    recipient: str
    message: str

    def __post_init__(self) -> None:
        if not self.recipient or not self.recipient.strip():
            raise ValueError("recipient must not be blank")
        if not self.message or not self.message.strip():
            raise ValueError("message must not be blank")

    def formatted(self) -> str:
        """Return a fully-formatted greeting string."""
        return (
            "╔══════════════════════════════╗\n"
            f"║  {self.message}, {self.recipient}!  ║\n"
            "╚══════════════════════════════╝\n"
        )


# ---------------------------------------------------------------------------
# TimeOfDay
# ---------------------------------------------------------------------------

class TimeOfDay(Enum):
    """Simple enumeration used to determine the part of the day."""

    MORNING = "Morning"
    AFTERNOON = "Afternoon"
    EVENING = "Evening"

    @staticmethod
    def of(hour: int) -> "TimeOfDay":
        """Map an hour (0–23) to the appropriate :class:`TimeOfDay`."""
        if hour < 12:
            return TimeOfDay.MORNING
        if hour < 17:
            return TimeOfDay.AFTERNOON
        return TimeOfDay.EVENING


# ---------------------------------------------------------------------------
# season_of
# ---------------------------------------------------------------------------

def season_of(month: int) -> str:
    """Return the meteorological season for the given month number (1–12)."""
    if month in (12, 1, 2):
        return "Winter"
    if month in (3, 4, 5):
        return "Spring"
    if month in (6, 7, 8):
        return "Summer"
    return "Autumn"


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> None:
    """Entry point – prints a greeting and today's date information."""
    today = date.today()
    hour = datetime.now().hour

    salutation_map = {
        TimeOfDay.MORNING: "Good morning",
        TimeOfDay.AFTERNOON: "Good afternoon",
        TimeOfDay.EVENING: "Good evening",
    }
    salutation = salutation_map[TimeOfDay.of(hour)]
    greeting = Greeting("World", salutation)

    sys.stdout.write(greeting.formatted())

    info = (
        f"Python version : {sys.version}\n"
        f"Today's date   : {today} ({season_of(today.month)})\n"
    )
    sys.stdout.write(info)


if __name__ == "__main__":
    main()
