# generated by AI in Github cloud
from __future__ import annotations

import sys
from dataclasses import dataclass
from datetime import date
from enum import Enum, auto


# generated by AI in Github cloud
@dataclass(frozen=True)
class Greeting:
    """Immutable value object holding a greeting message."""

    recipient: str
    message: str

    def __post_init__(self) -> None:
        if not self.recipient or not self.recipient.strip():
            raise ValueError("recipient must not be blank")
        if not self.message or not self.message.strip():
            raise ValueError("message must not be blank")

    def formatted(self) -> str:
        """Returns a fully-formatted greeting string."""
        return (
            "╔══════════════════════════════╗\n"
            f"║  {self.message}, {self.recipient}!  ║\n"
            "╚══════════════════════════════╝\n"
        )


# generated by AI in Github cloud
class TimeOfDay(Enum):
    """Simple enum used to represent time of day."""

    MORNING = auto()
    AFTERNOON = auto()
    EVENING = auto()

    @classmethod
    def of(cls, hour: int) -> TimeOfDay:
        """Factory method – maps an hour (0-23) to the appropriate TimeOfDay."""
        if hour < 12:
            return cls.MORNING
        elif hour < 17:
            return cls.AFTERNOON
        else:
            return cls.EVENING


def season_of(month: int) -> str:
    """Returns the meteorological season for the given month (1-12)."""
    if month in (12, 1, 2):
        return "Winter"
    elif month in (3, 4, 5):
        return "Spring"
    elif month in (6, 7, 8):
        return "Summer"
    else:
        return "Autumn"


def main() -> None:
    today = date.today()

    time_of_day = TimeOfDay.of(today.day % 24)
    salutation_map = {
        TimeOfDay.MORNING: "Good morning",
        TimeOfDay.AFTERNOON: "Good afternoon",
        TimeOfDay.EVENING: "Good evening",
    }
    salutation = salutation_map[time_of_day]

    greeting = Greeting("World", salutation)
    print(greeting.formatted(), end="")

    info = (
        f"Python version : {sys.version.split()[0]}\n"
        f"Today's date   : {today} ({season_of(today.month)})\n"
    )
    print(info, end="")


if __name__ == "__main__":
    main()
