# generated by AI in Github cloud
from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from datetime import datetime
import sys


# generated by AI in Github cloud
@dataclass(frozen=True)
class Greeting:
    recipient: str
    message: str

    def __post_init__(self) -> None:
        if self.recipient is None or not self.recipient.strip():
            raise ValueError("recipient must not be blank")
        if self.message is None or not self.message.strip():
            raise ValueError("message must not be blank")

    def formatted(self) -> str:
        return f"""╔══════════════════════════════╗
║  {self.message}, {self.recipient}!  ║
╚══════════════════════════════╝
"""


def time_of_day(hour: int) -> str:
    if hour < 12:
        return "morning"
    if hour < 17:
        return "afternoon"
    return "evening"


def season_of(month: int) -> str:
    if month in (12, 1, 2):
        return "Winter"
    if month in (3, 4, 5):
        return "Spring"
    if month in (6, 7, 8):
        return "Summer"
    return "Autumn"


def render_output(today: date, hour: int | None = None) -> str:
    effective_hour = datetime.now().hour if hour is None else hour
    current_time_of_day = time_of_day(effective_hour)
    salutation = {
        "morning": "Good morning",
        "afternoon": "Good afternoon",
        "evening": "Good evening",
    }[current_time_of_day]
    greeting = Greeting("World", salutation)
    info = f"""Python version : {sys.version.split()[0]}
Today's date : {today} ({season_of(today.month)})
"""
    return f"{greeting.formatted()}{info}"


def main() -> None:
    print(render_output(date.today()), end="")


if __name__ == "__main__":
    main()
